### ISSUE TITLE
Communication to players / steam users is not honest

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1166]
devs continue to give impression that the game is almost ready to be released on steam and that soon there will be many many players, and that only polishing is needed.
Actually the game is no closer to being release-worthy than it was 3 years ago, there are multiple different lobby-systems in parallel development, every new version of zero-k.exe lobby bombs online playercount into single digits on weekends.

How to fix:
Stop promising things and and stop weasling around and post an honest update on situation.

**Comment by Licho1** [comment]
I'm simply following this plan https://docs.google.com/spreadsheets/d/1_l117qQxgc8lk8D66oPFIWjngl7cWKnsMoIdHIDuiSI/edit#gid=0

Don't recall promising imminent steam release in recent months.

**Comment by knorker** [comment]
I'm simply following this plan https://docs.google.com/spreadsheets/d/1_l117qQxgc8lk8D66oPFIWjngl7cWKnsMoIdHIDuiSI/edit#gid=0

It is your honest opinion: "Multiplayer GUI 100% finished" ?

**Comment by Licho1** [comment]
for lobby? Yes

**Comment by knorker** [comment]
"ZKL" is not even used anymore, how can it be finished

**Comment by Licho1** [comment]
Chobby = Zero-K lobby

**Comment by knorker** [comment]
zeroK lobby =  Zero-K lobby
springweblobby =  Zero-K lobby
new rewrite =  Zero-K lobby
Chobby =  Zero-K lobby

and it was always "GUI 100%" ...lol?

I assume the open issues are to make it go to 200%

**Comment by knorker** [comment]
mission campaign:
what people were told:

"KingRaptor is making a singleplayer campaign and seems to be pumping out missions. "

"We already have some tutorial missions and campaigns - not yet integrated - but more need to be written and they will all require some polishing. "

"We want to release something at least with decent and easy to find local singleplayer. The content for this is fairly advanced, we have some pretty good skirmish AIs and quite a few missions have been produced."

Actual situation:
work had long stopped

**Comment by KingRaptor** [comment]
I like how you don't bother linking the actual posts because you either knew the timestamps would show your insinuation to be utterly false, or just didn't care if it was false.

["KingRaptor is making a singleplayer campaign and seems to be pumping out missions."](https://springrts.com/phpbb/viewtopic.php?f=90&t=35081&p=578104#p578104)
2016-06-11 (5 months ago)

["We want to release something at least with decent and easy to find local singleplayer. The content for this is fairly advanced, we have some pretty good skirmish AIs and quite a few missions have been produced."](http://steamcommunity.com/sharedfiles/filedetails/comments/247032802)
2016-02-17 (9 months ago)

["We already have some tutorial missions and campaigns - not yet integrated - but more need to be written and they will all require some polishing."](http://steamcommunity.com/sharedfiles/filedetails/updates/247032802/1476799847)
2016-10-26 (16 days ago)

Work dates:
- Last commit on repo Zero-K-Campaign2 was 27 days ago
- Last commit on repo Zero-K-Missions was 12 days ago
- Announcement of termination of work was 46 hours ago

So I guess by "had long [stopped]" you mean "in the future".

The last two quotes would also be entirely true even if I'd stopped work on campaign three years prior.

At this point it's clear to me that you're not in the least bit interested in whether your accusations against the team contain any truth whatsoever. Coupled with your recent history of shitposting in general, I think we can dispense with your presence on the project.
