### ISSUE TITLE
Make elo changes publicly visible

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1168]
This would allow people like manero to better understand what's going on and avoid unneeded discussions like http://zero-k.info/Forum/Thread/22917.

Talking about this:
![ELO](https://i.imgur.com/TiahHk8.png)

It won't make ELO any more public than it already is, as one has to parse all battles in order to calculate ELO just from relative changes(and once all battles are parsed one can calculate it anyway).

**Comment by knorker** [comment]
Discussed endless before, with all possible arguements. (That elo is visible ingame and in replay files, that it would make the system more transparent, that it is at best 'security' by obscurity)
mapfeatureres are not interessted to make elo public again because it is one of the last things that keeps them special/relevant.

**Comment by DeinFreund** [comment]
It's not about making elo visible, just elo changes.
