### ISSUE TITLE
AreYouReadyUpdate should tell players about their particular battle

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1208]
The server should know which players should go to which battles by the time AreYouReady is sent. The only way for players to end up in different battles is for someone to reject their battle. Therefore the matchmaker should send QueueReadyCounts for the particular battle that the player is participating in. The global QueueReadyCounts are less useful but may still be sent.

**Comment by Licho1** [comment]
This will reveal game size...

**Comment by Licho1** [comment]
Also it can be misleading, you can have full battle confirmation - like 4/4 and it can still fail, because someone else outside your battle refused.
Likelytoplay tries to mitigate that, it constructs new proposed battles every time someone readies and signals that you are in those.

But sending those newly generated proposals makes no sense either, because until you have full battle you are not in any proposal..
