### ISSUE TITLE
Proper restart warnings

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1244]
Implement a big red button to queue restart.

Hosts will then give a 60/30/15/5/1 minute warning to the players. Afterwards the players are kicked with a restart message, so they don't just randomly lose connection.

The restart should be indicated on the site as well.

**Comment by Licho1** [comment]
its not clear how to do it, only way is for human to click stuff after a given time and do a warning

**Comment by Licho1** [comment]
this is really for open discussion .. should we arrange some deployment times?
should it be announced by humans? (is tech solution really needed?)
or maybe automated daily deployment?
i dont see here what/how to code..

**Comment by KingRaptor** [comment]
A general **!announce** command that writes in every channel (or makes a popup message) and can get attention of people inside battle rooms/ingame would be useful for this and other things. (Although having to manually do it at the 60/30/15/etc. marks is a bit of a pain)

Automated deployment would still need advance warning in lobby server. It might also cause unwanted constraints in dev cycle (anything in master that cannot go into stable _must_ be reverted before the deployment, instead of just having to fix it ASAP).

**Comment by Anarchid** [comment]
Cherry-picking hotfix commits into stable from master works, just as pushing directly to master.
