### ISSUE TITLE
Matchmaker room requirements.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1254]
- [x] Battle rooms need to have a status tag to say whether they are matchmaker games. See https://github.com/Spring-Chobby/Chobby/issues/307
 - [x] Passwording a game is insufficient for matchmaking. If these games are to be spectatable then it must be possible to connect them once they are running without joining the room or supplying a password. The same applies to dropping from the game and attempting to rejoin. A player must be able to rejoin without knowing the password.
 - [x] I intend to completely hide the existence of the matchmaker battleroom. Post-game chat should be carried out within the hosted game. For this I think that the game server should be killed one minute after the game ends (or when everyone leaves). Currently it is killed three seconds after the game ends so there is no time for chat.

**Comment by Licho1** [comment]
GoogleFrog, room is password only AFTER game ends. 
After it ends room is zombified, it cannot be started again and nobody can join it, it's just so that people can chat afterwards.

You don't need any password to rejoin and you don't need to join the room to join ingame. What makes you think you do? You just use requestconnectspring and that's all.

I would not hide running mm battles and not even debriefing rooms. It gives important impression of activity and lets people track what others are doing.

Adding mark that room is MM room and that its in zombie state (battle ended, passworded) is trivial. I might instead just hide it from clients after battle ends though (while letting people in remain there).

**Comment by Licho1** [comment]
Notes: expose ismatchmakerflag
Close room when game ends
Block room entry
Move people to special channel or produce debriefing message when game ends

**Comment by Licho1** [comment]
Verify that closing mm room fixes https://github.com/Spring-Chobby/Chobby/issues/332

**Comment by GoogleFrog** [comment]
How? Can running MM on test server achieve that? For the verification try ticking "Debug for MM" in settings to view the MM rooms.

**Comment by Licho1** [comment]
Oh its not yet implemented, when it is its just a remark for me to post a notice on chobby and retest chobby.

**Comment by Licho1** [comment]
I mean the instant closing of game room isnt implemented yet, pending debriefing message.
