### ISSUE TITLE
Make casual elo visible

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1262]
Casual elo should be visible because here are the effects of the current system:
 * Team and 1v1 elo has been merged into a single value.
 * That single value is hidden from everyone.

This is because MM does not really exist in the present state (it is not even released) so it is futile to say people should use MM if they want ranking and visible skill improvement. The MM elo is effectively a confounding number which only correlates to the skill used for balancing in the most common type of game. The reality is that people use the custom rooms for their skill comparison and advancement. I don't expect the situation to change for at least three months (very conservative estimate) and I think that is too short of a time to leave rank display effectively broken.

At least send the elo used to balance the game into the game to be displayed as their rank (ranks differing is not all that bad in comparison). This is a highly requested feature. Casual elo may as well be shown everywhere so replaced the "casual rank" with a "casual balance rating" which is a number, not a rank. I'm not sure how showing casual rank but not elo was supposed to decrease elo stress. 

Possibly show casual elo for site and lobby icons, I consider this one optional as icons have not previously shown rank (in a way anyone could understand). The colourful badge may still be reasonable to leave as an incentive to try MM.

**Comment by Licho1** [comment]
Difference is, that we only show the number for person himself.
If the claim is , that people want to see it to improve, I'm fine showing elo for self too.

But why do they need to know skill of other people?

**Comment by sprunk** [comment]
As far as I can see most people complain about invisible rank because they (think they) play very competitively: they want as much information ingame as possible to help them win, and then as much information outside the game to track improvement relative to others.

I don't think the current people are going to change at all under current circumstances. The MM does not provide large games.

I think the solution would be to allow large games through the MM and remove any visibility of casual (including rank and top50). This way if people want to see rank (for whatever reason), that means they are competitive and can play through the MM.

**Comment by db81** [comment]
Google's point is that right now people aren't playing MM, and he doesn't expect them to, so hiding "casual" elo and ladder is equivalent to hiding elo and ladder period.

I absolutely don't think people are very competitive or even think they're very competitive. Almost no one even approaches the point where they're using "as much information as possible to help them win".

It's just very nice to be able to take a look at the player list and see what you should expect from what enemy and ally and how much attention you should pay to them, and to see that at a glance. Otherwise you'd have to remember which player is good and which is a nub and that's annoying.

**Comment by Licho1** [comment]
If "casual" elo is fully visible (atm it is partially), why to have two elo's at all?
Why to have ranked and unranked games?
We could have every game as ranked and just have single elo rank/value and be done with it. 

All really custom games will be unranked, everything else => ranked.
Single elo to rule them all.

**Comment by GoogleFrog** [comment]
Changes:
 * Remove "Rank (casual): X" from user page. Its not useful and makes casual seem like its supposed to be competitive.
 * Add elo number to the Top 50 list for casual. The Top 50 are going to be competitive in the current environment so we may as well have numbers.
 * Send casual elo ingame for games balanced with casual elo. This allows them to judge their enemies.

**Comment by Licho1** [comment]
number 3) means that casual elo is visible to everyone (ingame), and that rank icons mean every time something different.

Do you seriously propose this as a final state? If not then we should think again.

**Comment by sprunk** [comment]
Number 2 should also be a non-final thing imo (showing the top50 casual at all).

> All really custom games will be unranked, everything else => ranked.
> Single elo to rule them all.

This is very good but the MM would have to support large teams.

Else either large teams are unranked (imo that's ok but current people want to be ranked and would rage) or you allow MM elo to be modified through non-MM games (bad, in a room you can pick who to play with etc).

**Comment by Licho1** [comment]
Basically I see three options (other than reversals):

1) casualisation - do what GF suggests, hide rank from self, send just order to ingame. Top 50 will se rank incl. elo

2) more competition - show casual elo, send to ingame (either to self or to all teammates)

3) even more competition - total elo merge, no glaive killed in vain

**Comment by Licho1** [comment]
implemented google's suggestion by 6757a908218d6b0a4a33495626e30c837813e463
