### ISSUE TITLE
Improve scaling of ZKLS for high player counts

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1284]
Target = 1000+

- [x] handle big channels
- [x] remove global joined/left battle, instead attach battleID to user structure
- [x] only send User data to: Friends, ClanMates, People in same channels, People in same battles
- [x] make ban/login processing async where possible
- [x] periodic update of battle headers (instead of after every join)

Also 

- test rate limiter on logins 
- upon friending send channel joined/user update as needed
- improve player joined/left battle messages

**Comment by db81** [comment]
I still think it's better not to split channels and instead show the number of people in the channel and only show friends and clanmates in the list.

Think of the logistics of how it will be used. You go to #zk to talk to the ZK community at large, if you have to hop potentially 10 (!) channels to find the right people and keep your hand on the pulse, no one will use it.

**Comment by knorker** [comment]
> Think of the logistics of how it will be used. You go to #zk to talk to the ZK community at large, if you have to hop potentially 10 (!) channels to find the right people and keep your hand on the pulse, no one will use it.

aka the problem that happend with spring chat: There was a #main chat that all players joined. Was very good to organize matches and general blabla. Then all the lobbies begun to use different default channels and the chat was dead. 
(Plus annoyed players leaving the channel because there was too much spam http://zero-k.info/Forum/Thread/20386)

**Comment by Licho1** [comment]
@db81 
The issues with non splitting is, that with too many people, it might be impossible to simply hold a conversation - too many people talking. 
Hiding players instead makes it feel empty (even if there is some counter I think).
Counter itself means updates have to be sent whenever player joins/leaves.

What others think? Split or hide players?

**Comment by db81** [comment]
If you worry about #zk devolving into an endless stream of shitposting, that will be a problem, but it's *already* a problem occasionally, all it takes is Skasi and someone else posting ASCII Soviet flags. It still provides social cohesion and a way to ask for help, especially if we moderate it a bit. Splitting it into disconnected shards defeats the whole purpose.

https://sketch.io/render/sk-cae1041b7cb45ebedabbba52bc8053f3.jpeg looks sufficiently non-empty, it's actually preferable because you don't care about all people, so the full list makes it hard to see who's online.

> Counter itself means updates have to be sent whenever player joins/leaves.

They don't have to. You send updates every 3 minutes. Every 5 minutes. Doesn't impact usability.
