### ISSUE TITLE
Outdated/missing unitpics in UnitGuide/Site

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1291]
![hermit](http://manual.zero-k.info/unitpics/spiderassault.png)
If the above depicts a hermit, this issue has been resolved.

Pictures of modern units(like Redback) are missing entirely. The guide should also be regenerated with new stats/units(like Wasp).

**Comment by KingRaptor** [comment]
I don't suppose anyone has FTP access to packages.springrts.com?

**Comment by Licho1** [comment]
No access... but I think it meant our site..

**Comment by DeinFreund** [comment]
Seems github mirrored the image locally, anyway I'm talking about the images in http://manual.zero-k.info/unitpics/spiderassault.png

As the manual has been moved to wiki I'm not sure whether these pictures are still in use at all.

**Comment by Licho1** [comment]
This thing is auto copied on each zk stable by teamcity script. Is it not working?

**Comment by DeinFreund** [comment]
Check the picture. (That's a very outdated hermit)

**Comment by KingRaptor** [comment]
Teamcity says it runs without errors, but actually checking FTP shows that neither `www/img/unitpics` nor `zkmanual/www/unitpics` on zero-k.info have been updated since July 2016 (except solar and mex for some reason).

It's not even a matter of not overwriting existing files on server, the unitpics for new ships aren't in.

**Comment by Licho1** [comment]
The script does not look like it could ever work:

Copy unitpics to avatars and luarules to awards but no copy for unitguide..
Also if errorlevel 1 exit 0 -> removes errors.

robocopy unitpics c:\projekty\zero-k.info\www\img\Avatars /e
robocopy LuaRules\Images\awards c:\projekty\zero-k.info\www\img\Awards /e
if errorlevel 1 (
  exit 0
)

**Comment by Anarchid** [comment]
The teamcity script is exclusively for avatars/awards. The entire process of generating manual is completely separate iirc.

**Comment by Licho1** [comment]
It seems to be generated by slow-wiki now.

**Comment by DeinFreund** [comment]
Looks like a hermit now.

**Comment by KingRaptor** [comment]
I manually uploaded new unitpics to ZK FTP a month or two back (and made the mediawiki pages use them).

**Comment by Licho1** [comment]
where is the new manual generated? Is it automated?

**Comment by Licho1** [comment]
oh we have our own generator, it sits in "zkmanual" folder (zero-k.info\zkmanual) for quite some years, it runs using lua to update *old* manual, but has .bat launcher.
There is no shell .. and the tool is in zk tools repo in github..
So you should have started from taht instead of from some outdated spring repo..
