### ISSUE TITLE
All teams marked dead on battle end

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1310]
http://zero-k.info/Battles/Detail/434219
http://zero-k.info/Battles/Detail/434216

**Comment by Licho1** [comment]
your commit seems to have no effect, because gameendedok is set to true just below it .. its always false at that point

**Comment by sprunk** [comment]
In multiplayer each client sends a GameOver message on its own so this code runs multiple times.

The first time it marks people outside the game as dead, and then everyone as ingame = false. Then people still alive are marked winners so winning team is correct on the replay page.
The next time it marks everyone as dead because previous time it marked everyone ingame = false.

**Comment by Licho1** [comment]
Ok, thanks! I thought dedi filters this

Dne 28. 10. 2016 4:41 napsal uživatel "sprunk" <notifications@github.com>:
