### ISSUE TITLE
Website registration

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1327]
* There can always be players who encounter some issue with their lobby and are unable to create an account, they should be able to ask for help on the forums. http://zero-k.info/Forum/Thread/23184
 * The website seems very "closed community" for outsiders. 
 * There's no way for people to ask around before downloading the game. (On steam it's common to find "Should I get this game?" threads in the game forums)

But
 * Enabling website registration increases the chance of spam

I would suggest employing either some kind of trick question to get rid of completely automated spammers or a well-tested captcha. Besides that it'd make sense to throttle the amount of registrations allowed per IP so it's not possible to create a million accounts in a second. The same could be applied to posts: A player can't create no more than playerlevel + 10 posts per day.

**Comment by shaun0x00** [comment]
And then there are the server outages which happen regularly and are very well tolerated by long-term players, because they know it happens regularly. But for newcomers, they may find it unacceptable or suspicious that the server they rely on to play the game they just installed is now offline.

So you need a place outside of that small closed community to announce why the server is down/when the server will recover...

I can foresee that asylum enforcement may be harder outside of that small closed community, but if you want to grow it, maybe you'll consider making some compromises... (it's a dangerous world out there).

**Comment by Licho1** [comment]
We could have steam openid registration now. That will block most non-specialized bots.

**Comment by Licho1** [comment]
Discord works around it I hope, no need for registration.
Steam registration is possible but it can invite even more trolls we cannot detect properly.
Reopen if you disagree.
