### ISSUE TITLE
Wrapper mission support

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1329]
I thought there was a ticket but now I cannot find it. The wrapper needs to download the mutator files for some set list of missions to Spring/games. The wrapper should create one folder per mission in Spring/missions. Each subfolder should contain a standard json file which tells chobby how to run the mission which will mostly consist of:
 * Name
 * Dependancies
 * Script file path
 * Image file path

The image can be disabled as a mission thumbnail. The script file should be in the same folder.

**Comment by Licho1** [comment]
Ok will look into it this wekk

**Comment by Licho1** [comment]
Pr-downloader cannot download ZK missions. It no longer uses ZK servers.

**Comment by Licho1** [comment]
Wrapper makes folder "missions" int the chobby/isolation mode root.
It contains missions.json - serialized information about all missions and mission images, named as <MissionID>.png  
Missions.json also contain scripts

Missions themselves and their dependencies are downloaded and put into correct folders (chobby can assume they are presnet)

Note that for script missions for some historical reason the runner should replace %MAP% %MOD% and %NAME% in the script.
We can also change it and pre-replace map and mod since they are known.
