### ISSUE TITLE
Newbie forum section

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1344]
I think hedgehogs should have his own forum section.

While his posting frequency might be slightly above the recommended daily dosis, people like him shouldn't be discouraged from asking questions (and there will be a lot more poeplers to come). It would be nice to have it separated into a category besides general discussion, so not everybody gets spammed by (for them) uninteresting discussions.

This kinda fits into the Strategy/Tips section, although it would probably be preferable to have "professional" guides separated from "How to kill ddm?".

**Comment by db81** [comment]
I think if we're doing that, maybe we should go all the way and let users mute certain forum categories. Muted categories function like Asylum, they don't show notifications unless it's a thread you posted in.

Would also make categories a bit more useful because atm everyone just looks at latest posts and the only time you remember they even exist is when you're making a thread or when you're searching for something.

**Comment by Licho1** [comment]
I dont understand what is actually requested/needed.

**Comment by db81** [comment]
Orf complains about seeing too many hedgehogs threads in latests posts. I muse at length and then float the idea of an unsubscribe button for threads like on github. I still think that's a good idea, the rest can be ignored.
