### ISSUE TITLE
mission editor cannot export sdd to existing folder

### ISSUE THREAD

**Issue by silentwings** [ZeroK-RTS/Zero-K-Infrastructure#1349]
The mission editor can "create mutator -> .sdd" and save a mission in sdd format to a folder that it creates.

Afaics it cannot save a mission in sdd form into an already existing folder called XYZ.sdd.

**Comment by KingRaptor** [comment]
When you have `myFolder/foo.sdd`, export as `myFolder/foo.zip` and it will replace `foo.sdd`.

(It uses this silly way because that was the most expedient way to deal with the fact that if you try to enter `foo.sdd` as the save file directly the dialog thinks you want to explore that folder instead. I probably ought to use a [FolderBrowserDialog](https://www.dotnetperls.com/folderbrowserdialog) instead, would that be less confusing?)

**Comment by KingRaptor** [comment]
On second thought, FolderBrowserDialog is too much of a pain for the user. I'll leave things as they are and just tweak some text in the .sdd export dialog to make it clearer how it works.
