### ISSUE TITLE
Prevent server meltdown

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1426]
To prevent server meltdown prepare mitigation strategy for too many players online.
It can include:
 - queue when connecting to lobby server
 - limited number of running "hosts" 
 - temporary ban of spectators
 - temporary block of sales on steam 
 - allow local personal hosting (with NAT traversal) and without awards etc.

Suggest more ways.

**Comment by Licho1** [comment]
The elephant in the room are dedicated servers. Will single machine handle 100 running spring dedicated servers with 1000 people? How is our UDP traffic?

**Comment by shaun0x00** [comment]
This nearly 3 years old wiki entry was an attempt to highlight some perfectly expected issues.

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/wiki/Infrastructure-performance

These kind of tests are only possible by cooperating with the server owner... which is you. Since all attempts to raise the issue that the server should be owned by the project (not by an individual) have been met with resistance, I see that this hasn't progressed much. "Suggest more ways"... yeah.

Regarding the "elephant in the room", is your new infrastructure unable to spawn dedicated-runners on multiple servers? It would be sad if in 2017, you are still opting for the option "get the largest machine we can to handle the load" rather than "spread the load over a cluster", for load-sharing and availability (fault tolerance) reasons.

**Comment by Licho1** [comment]
Issue is we are unable to test the load on dedicated servers.
How do we emulte so many spring as clients?
Testing load on lobby was done and it's fine now (n^2 issues were removed).

**Comment by shaun0x00** [comment]
Do not emulate them, run real spring instances on injector machines. (If you try to emulate it, you risk not having convincing data to get spring devs to fix the custom layer running providing ordered+reliable comm over udp protocol. It generates twice as much traffic as it should when it spirals into retransmission storm...)

I've been off-hook long enough to ignore whether spring-headless is still a valid option... if it is, you can just rent a few amazon/azure/whatever VM and use those or ask your players to run many.

If headless is not an option, leverage your current players machines as injectors?
I'd be surprised if your players machines were unable to cope with several instances of spring simultaneously, with lowest gfx settings and just 2 bots in 1v1 (or missions?), in order to generate traffic.

**Comment by Anarchid** [comment]
Headless should be in good health. It worked earlier this year.

**Comment by Licho1** [comment]
Stragies in place/progress:

 * steam install runs completely offline, singleplayer/skirmish works without conneciton and connection is not made by default
 * ability to reliably adjust server address
 * server-less p2p COOP hosting (depends on steam and google STUN server, but not on ZKLS)
