### ISSUE TITLE
Main site https redirects to non-https

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1436]
Entered
`https://zero-k.info`

Was redirected to
`http://zero-k.info/?ab=c&utm_expid=40620291-0.724Oclx9TnuQRzZxdj7hbw.2`

**Comment by Licho1** [comment]
this should be temporary (AB test)

**Comment by shaun0x00** [comment]
Is it a 7-days long benchmark, or just a forgotten issue? Some people are connecting over insecure networks and if nothing is holding back this long awaited change, can you enable it back please?

Also...
https://webmasters.googleblog.com/2014/08/https-as-ranking-signal.html

And if benchmark is done, are the results available somewhere?

btw, I doubt HTTPs is the cause of performance problems (nor that it is meaningful to benchmark the site if it is not configured as it will be used):
https://www.keycdn.com/blog/https-performance-overhead/

**Comment by sprunk** [comment]
As far as I know the AB test is not related to performance but different preview trailers on the homepage.

**Comment by shaun0x00** [comment]
Oh right. Does it mean that once the "AB benchmark" is done, the right trailer will be picked... and release will be done, only to later discover that there is a performance problem due to the lack of "ab benchmark" (apache benchmark)?

It should have been clear to me that what others were contributing was ignored, because expecting a benchmark before release is "losing touch with reality" as the minions put it...
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/wiki/Infrastructure-performance

**Comment by Licho1** [comment]
benchmark still running, will fix itself when its done
