### ISSUE TITLE
MM: bias bigger games

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1486]
Slowly decrease "min size" for each player, allow only sizes min of players min size.

**Comment by DeinFreund** [comment]
Problem with this is that currently there'll always be that one left out guy sitting in the queue for 20 mins until the prevoius MM game is over. Then the other people rejoin MM and because he's been sitting there forever it instantly makes a 2v2, leaving the remaining players to wait. This applies to both the current and this system.

Using max of player min size but keeping max of player max elo difference should help with this.

**Comment by Licho1** [comment]
If we use max, it means there won't be "insta join" .. inst start battle.
