### ISSUE TITLE
SteamOnline issue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1533]
I had trouble connecting with my steam account. This is what I did:
 * Start non-steam chobby.
 * Start steam.
 * Non-steam chobby finishes loading, does not receive SteamOnline.
 * Closing and restarting non-steam chobby does not receive SteamOnline.
 * Close chobby, update ZK on steam.
 * Starting non-steam chobby does not receive SteamOnline.
 * Starting ZK via steam does not receive SteamOnline.

To fix it I closed chobby and Steam then started Steam and started non-steam chobby.

**Comment by GoogleFrog** [comment]
Most of the ticket is superuser stuff. The part that worries me was that I was able to launch ZK with steam and not get SteamOnline. There may be other ways of causing this bug.

**Comment by Licho1** [comment]
Not specific enough.
Was the copy steam copy? Was it stable or test? Was it modified in any way? When was it updated? 

Where is the infolog_full.txt ? Did chobbyla report steamonline? If not what was the error message?

Also if you first start chobby and then steam, check only happens every 30s (because it is expensive and we dont want to lag non-steamers).

**Comment by GoogleFrog** [comment]
@KingRaptor had the same issue https://github.com/ZeroK-RTS/Chobby/issues/169

**Comment by Licho1** [comment]
Changed refresh rate so it should not happen, if it does please report again.
