### ISSUE TITLE
Unable to read data from the transport connection crash

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1641]
This is a very common error: https://github.com/ZeroK-RTS/CrashReports/issues/410

**Comment by gajop** [comment]
I think you are misinterpreting that infolog. To me it seems that Spring/pr-downloader crashed and Chobby.exe detected the TCP socket closing.

**Comment by GoogleFrog** [comment]
This is a better example: https://github.com/ZeroK-RTS/CrashReports/issues/424

What else is in the infolog there?

**Comment by gajop** [comment]
That seems like the engine crashing when it's being closed. This happens a lot unfortunately, but the engine devs didn't really care for it because the game is over anyway. Now that we have LuaMenu and these wrapper programs it's a different story...

PS: Just to be clear, this message is being sent by Chobby.exe from what I can see: `Chobby.exe Information: 0 : ZkData.TcpTransport socket disconnected: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.`. It will always be there when it crashes unless Licho changes Chobby.exe logging

**Comment by Licho1** [comment]
Yes, it will always be there. It is only information, it would be different story had it closed mid-game, but if socket closes when spring crashes or freezes, that's normal.
Nothing to fix for wrapper.. engine/pr-downloader needs fixing.
