### ISSUE TITLE
replay search - minimum elo

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K-Infrastructure#1744]
It would be nice if we could specify a minimum average elo for replays to show up in a search

**Comment by DeinFreund** [comment]
Due to Elo being time independent, how do you imagine this? Should every battle store each participants' pre-battle elons? Do you only want to use latest rating? Do you want to use WHR and get the estimate rating for each player at that time(will be different to the WHR back when the battle was played but should be more accurate)?

I think the feature would be nice, I'd limit it to skill groups for simplicity. I'd prefer to directly integrate it with WHR though instead of trying to do it some way with Elo now which would only lead to less accurate results.

**Comment by Licho1** [comment]
I think we can base it on current elo that is quite simple.
