### ISSUE TITLE
Missions: Streamline start.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1786]
Remove "press any key to continue" and the 3s game start delay. The delay can be removed with `GameStartDelay = 0` in the startscript. @KingRaptor can you update missions for this?

**Comment by KingRaptor** [comment]
I implemented "press any key to continue" to give the game some wait time during the preload phase, because in missions I observed a brief period of single-digit FPS that takes a few seconds to clear – you don't want the game starting during this period (especially if it has a starting cutscene).

It's probably not strictly necessary for the tutorials (both because they're less resource intensive and because nothing happens at start without player input), so I can remove it. If https://github.com/ZeroK-RTS/Zero-K/issues/2427 is fixed that should also help.

**Comment by KingRaptor** [comment]
Game start delay removed.

I think Sprung gave good reasons on Discord for keeping the press-to-continue, so at present I'm considering this solved.
