### ISSUE TITLE
Linux steam install issue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1814]
https://github.com/ZeroK-RTS/CrashReports/issues/2137

**Comment by Sortale** [comment]
in continuation

https://github.com/ZeroK-RTS/CrashReports/issues/2140

this is the crash log when I start chobby according to command line on download page [similar to many previous reports]

It is noted that wrapper was able to download a lot of the game data before crashing here

**Comment by Sortale** [comment]
steam zero-k work on 64bit Linux mint after adding this command line
'sudo apt-get install mono-complete libsdl2-2.0-0 libopenal1'


seem like the previous problem was from spring 32 bit was improperly compiled, engine devs are aware, and told me that it should be fixed in some time. 

probably close this issue then?

**Comment by Sortale** [comment]
on virtual machine linux 64bit need
curl runtime library:

    sudo apt-get install libcurl3


curl development library:

    sudo apt-get install libcurl4-openssl-dev
inaddition to the usual dependency to run
this is peculiar because the same installation on a real machine do not require them

**Comment by Licho1** [comment]
new depts added to itch install page
