### ISSUE TITLE
Steam api is hindering install on obscure linux

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1815]
See this thread http://zero-k.info/Forum/Thread/24338

**Comment by GoogleFrog** [comment]
@Licho1 this is relatively important as we're losing testers to other lobbies and people using other lobbies are a source of confusing advice for new players.

**Comment by Licho1** [comment]
What makes you think that this is related to steam API? 
All I see there is this:
"Chobby.exe Warning: 0 : Spring exit code is: 127, assuming crash"

The launcher is designed to work perfectly fine withou steam api working or steam being present. 

He should try chobby again after having those openAL installed and then post infolog.txt

**Comment by db81** [comment]
Exit code 127 almost always means spring couldn't load some .so and that means there's not gonna be an infolog.txt. We should perhaps show a message to run `sudo apt-get install mono-complete libsdl2-2.0-0 libopenal1` when chobby sees spring crashing on linux with 127.

Perhaps this ticket should be about the confusing message from chobby that makes people think there's an error, but even then, Vermind told him that he can ignore that and now he's using chobby:
> How do you run Zero-K? I have the folder on my desktop, I open it, and right click on Chobby, and choose run with mono runtime, it then self updates, and the Zero-K lobby opens, is there a way to put Chobby on the desktop, so I can just left click to open? 

But he still wants to play BA or whatever so he goes on a wild goose chase to find a working lobby and then gets confused because he doesn't know logins aren't shared between the two servers. Eventually he figures out how to change his login in swl and now everything is fine.
