### ISSUE TITLE
itch.io Planetwars

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1838]
It seems planetwars are currently still WIP. 

Would it be possible to do a beta round for the itch.io release? We acknowledge that it isn't completed, but it's playable (and fun imo). Even if there are some things that are still to be implemented right now, testing should give us a better idea of what to work on.

**Comment by sprunk** [comment]
There's quite a lot to work on already: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues?q=is:issue+is:open+label:planetwars

**Comment by DeinFreund** [comment]
Yes, that's why it's still WIP. Does that mean it's unplayable? The main game isn't finished either.

From my experience with the last two PW (which had even more problems), they were still a blast to play. We should clearly mark is as experimental/in development and if people don't like it we can always disable it.

**Comment by GoogleFrog** [comment]
I think it is a bad idea to just run planetwars. I expect that treaties still do not work. In general there are a lot of vestigial mechanics in planetwars which are untested so could be broken. Also is is likely unbalanced. Here is what I would do without any infrastructure support (so all we can do is edit DB and constants):
 * Remove planetbuster.
 * Remove string connector.
 * Test all the treaties and remove the ones that do not work.
 * Set the artefact to cost a lot less energy, perhaps none.
 * Make the energy -> metal conversion much less efficient.

Here is what I would do with some infrastructure support, but not much:
 * Remove planetbuster.
 * Remove string connector.
 * Test all the treaties and fix the broken ones.
 * Add a DB key for reactivation cost. You can instantly pay X metal to reactivate a destroyed structure.
 * Remove automatic energy to metal conversion. This is to make early energy overproduction not a trivial decision.
 * Add a DB key to add metal income to a structure. Possibly use this key to make a mex that costs energy. The key may be useful to have.
 
Ideally we would have an accurate and full list of all the systems and mechanics of planetwars. In order to make good game design we need to know what everything does. Otherwise I feel like removing absolutely everything which is poorly defined in my mind. Create a document detailing the actual current planetwars mechanics if you want to help out in a relatively simple way. I don't think anyone quite knows how planetwars works. Remember the surprising effect of planetbuster.

See: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1705

**Comment by sprunk** [comment]
It doesn't mean it's unplayable but

>testing should give us a better idea of what to work on

There is a high probability this idea ends up being "yeah, all the tickets we found the previous round". Of course you can still find something new but you are guaranteed not to find problems caused by redesigns.

**Comment by sprunk** [comment]
>Remove automatic energy to metal conversion. This is to make early energy overproduction not a trivial decision.

This is doable without any infra support by setting the efficiency constant to 0.

**Comment by GoogleFrog** [comment]
I don't know the state of planetwars. I don't know which rare mechanics are hiding in some treaty or structure. I'd be much happier if there was somewhere which stated how planetwars works. Then it would be much easier to figure out what to change.

**Comment by DeinFreund** [comment]
This all sounds doable and sensible. I'm also for starting by first documenting everything as it is now.

My main goal for itch.io was to release the game as it is, so I'd leave out PW for now.
