### ISSUE TITLE
Fill out press kit

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1900]
Download /presskit/ and follow instructions.

**Comment by sprunk** [comment]
Doesn't seem to have happened for itch. Possibly it could be filled for Steam but the template would likely need to be rethought because it's standard for industry and we are not industry so many things don't even apply (no company, not based in any city so no address, author list has hundreds of people, history is extremely long and goes back into TA, ...)

Remarks from @GoogleFrog when he tried to fill it in:
>this xml will be difficult
>we don't fit a standard press kit
>its useful to step back and consider what this is for. The fact that we can't fill in many of the entries to me hints that if we simply fill in the remainder we will be left with something which isn't useful to anyone

**Comment by GoogleFrog** [comment]
I think filling it out is still reasonable and I didn't aim to do much press for itch.

**Comment by Licho1** [comment]
Presskit lives in ZK source codes "presskit" folder, you can edit, commit and see results on presskit.test.zero-k.info and presskit.zero-k.info

**Comment by DeinFreund** [comment]
Presskit has been filled out, `install.php` needs to be deleted from the presskit folder for it to become visible.

**Comment by Licho1** [comment]
deleted

**Comment by Connetable** [comment]
There's a presskit in the wiki (accessible via "About ZK"). Not sure if you're talking about the same thing.

**Comment by Licho1** [comment]
The actual presskit is here http://presskit.test.zero-k.info/  its a copy of the wiki

**Comment by Licho1** [comment]
tweak credits there as well

**Comment by DeinFreund** [comment]
Added new trailer. Credits look fine to me, coredevs are there.

**Comment by sprunk** [comment]
Release happened.
