### ISSUE TITLE
Expunge ELO references

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1924]
When the site says "ELO" it should say something like "Rating". This ticket can be delayed until WHR is known to be used long-term.

**Comment by DeinFreund** [comment]
ZK Elo wasn't really Elo either. WHR when displayed as a single number still works with the standard Elo win chance prediction formula. The only difference is in how this number is calculated.

Thus Elo is a lot more descriptive than Rating. Calling it WHR will be cryptic to most rating system experts even because of its rare usage.

**Comment by sprunk** [comment]
To the user it shouldn't matter what specific rating system we use. People might also not be aware that "Elo" refers to a rating system.

**Comment by DeinFreund** [comment]
There needs to be some reference on what the numbers mean besides higher = better. Otherwise we could also make the numbers less prominent.

**Comment by sprunk** [comment]
I think it's fine if a wikipage says that we use what is basically a modified Elo, if someone wants to know what the numbers mean.

**Comment by GoogleFrog** [comment]
A generic word like rating or skill is better than ELO or WHR.

**Comment by Licho1** [comment]
Yeah could be called skill or rating even if its elo formular for win.

**Comment by GoogleFrog** [comment]
I don't think that one line change has changed all references to ELO.
