### ISSUE TITLE
ZK now runs inside the bin folder on Linux

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1976]
After the update if you run zk from steam on linux it tries to run inside bin, thinks nothing is installed  and loses all settings and redownloads maps, missions, etc into bin. You have to manually run Zero-K.exe inside the steam folder to make it work correctly.

**Comment by Licho1** [comment]
Thats the .sh script people provided also for itch. I guess it does not work properly.
Was it better before? Issue was that previously it would not install dependencies.

**Comment by db81** [comment]
I mean, you can have it launch the wrapper in the right working dir and have it install deps. I think it's fine to have a script that checks deps and suggests to install them. I guess I'll fix this together with #1975 since it looks like you only have what people provide you with and can't test bash scripts.

**Comment by Sortale** [comment]
strange my .sh script should not touch root "bin" folder

and yes my sh script change folder level [i.e. instead of install folder it goes to install folder/bin ]

which was because it was intended for fresh itch installation not ongoing steam instalation.

I'll try to write that checking dep script when I have my next day off [long time away]

**Comment by lagerspetz** [comment]
Sortale, The Zero-K.exe is placed where the script is, and Zero-K.exe downloads game data to the same folder where it itself is, so having a "bin" folder is not possible.

**Comment by db81** [comment]
AFAIK that's no longer applicable.
