### ISSUE TITLE
The ladders are not updating

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2006]
First Login: 5 years ago, Last Login: 44 minutes ago
Competitive rank: 2. (2323 ± 26, Top 3.5%) Plot graph
Casual rank: 4. (2321 ± 23, Top 1.7%) Plot graph
Planetwars rank: Unranked, estimated 1446 ± 143 Plot graph

![image](https://user-images.githubusercontent.com/1318249/34853969-d67872d2-f78a-11e7-8d00-7d84e2ddcbcf.png)

Red rank on site as well.

**Comment by sprunk** [comment]
I see red on his user page but gray on ladders page.

**Comment by DeinFreund** [comment]
This is intentional, fealthas wasn't active so he didn't get his free rankup when the rank update was introduced. He'll have to rankup one rank at a time until he reaches his rank. 

Rankups are limited to one per victory, to maximize the amount of positivity. Rankdowns are also limited to one per victory.

The ladders not updating are an issue though.
