### ISSUE TITLE
Dotwars landing page background could be improved

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2151]
![image](https://user-images.githubusercontent.com/1318249/38287495-510c9d84-380e-11e8-9d5d-d0e9b212edee.png)
I think a nicer screenshot would be one that isn't dotwars. Perhaps a nice blue and yellow beach battle. The dark red is pretty oppressive and no unit models are shown.

**Comment by DeinFreund** [comment]
The background image should optimally have 1440p or 2160p resolution and most of the detail on the edges. Otherwise it's unfortunate to have these nice screenshots with cool things going on in the center of the screen being occluded by the website itself.

Maybe a closer view of an active front line could work, so that the line extends to both sides of the image.
