### ISSUE TITLE
[Fx]Drone has no icon

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K-Infrastructure#2264]
Infolog:
>Warning: Couldn't find texture "LuaUI/Configs/Avatars/droneheavyslow.png"!

**Comment by KingRaptor** [comment]
Fixed by changing Drone's avatar to `dronecarry`
(he was the only one with droneheavyslow, I set it manually a long time ago)

**Comment by sprunk** [comment]
Can be brought back, the unit itself that had broken buildpic. See https://github.com/ZeroK-RTS/Zero-K/commit/f3e50f29d720dab91819a8777a67b7142cfcf4d1

**Comment by KingRaptor** [comment]
Where are avatars loaded from? I put `droneheavyslow` in site's img/Avatars folder so I'd have expected it to be able to fetch from there.

(LuaUI/Configs/Avatars also has some images, but it seems obviously incomplete + outdated)

**Comment by sprunk** [comment]
Ingame avatars are ordinarily taken from `/unitpics`, with `/LuaUI/Configs/Avatars` used for the few that are not units. As far as I can tell they are never automatically fetched and can only end up there by actually being put directly in the repo. `droneheavyslow` is a unit name so its buildpic was supposed to be found in `/unitpics` but it was misnamed (as `droneheavy`) so both `[Fx]Drone` and the unit itself were broken (nobody noticed because drones aren't selectable, but you could open its page from the unit list).

Site always takes from `zero-k.info/img/Avatars` and stuff gets copied there from ZK's `/unitpics` when a stable gets built. That folder only receives new pics but is never cleared so still had the correct picture from before it got broken by a rename.

**Comment by sprunk** [comment]
Stable has since been made.

The query to execute, if desired, is
```sql
UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'droneheavyslow'
WHERE AccountID = 169802;
```
