### ISSUE TITLE
Some users cannot be selected using site combobox

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K-Infrastructure#2265]
For example the user Nav:
http://zero-k.info/Users/Detail/402524

If I type in the exact name to a player input text box I get a list of players which does not include Nav.

This means (perhaps among other things) that it seems to be impossible to create a tournament room for this user.

**Comment by maackey** [comment]
It looks like the user search pulls the first 10 results from users, first 10 results from forum, first 10 results from maps, etc. I'm guessing that somehow when searching for "nav" it comes after the first 10 results, but there are no more letters to narrow down the search, making them otherwise impossible to find.
