### ISSUE TITLE
Lower game start timer

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2309]
See https://github.com/ZeroK-RTS/Zero-K/issues/3087

>At least for 1v1 MM games. Currently you have like 180 seconds to pick a spot to drop your commander. This is too much - when you click accept in the lobby this means you are ready to play and it is expected you will be there. This game countdown time is not the time to go to the bathroom or something like that.
Drop to something more reasonable like 20s.

**Comment by Fealthas** [comment]
Then maybe something like 10 seconds after both finish loading?

**Comment by DeinFreund** [comment]
Sometimes you even have to rejoin  because of some bug. All this would achieve is forcing players into the game before they are ready. Is this something we want?

I'd suppose that games take long to start because either a player quits before the game starts or a player doesn't know how to place his commander. There must be another common scenario or why would you want to decrease the timer?

**Comment by sprunk** [comment]
Duplicate of #2981

**Comment by sprunk** [comment]
Well maybe this one asked to just reduce it without necessarily making it configurable but maybe it would've been bad to hardcode rules like this.
