### ISSUE TITLE
website - security - usercontent

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#237]
http://googleonlinesecurity.blogspot.ch/2012/08/content-hosting-for-modern-web.html

ZK does not use this mitigation technique that everyone else is using.

Combined with the years old "bug" of storing unencrypted passwords in cookies despite common sense, this can lead to total compromise.

https://www.owasp.org/index.php/Top_10_2013-A2-Broken_Authentication_and_Session_Management

**Comment by Licho1** [comment]
fixed, cookies no longer store pw hashes, site uses https and steam openid

**Comment by sprunk** [comment]
What about sanitising user uploaded content? Maps, clan background images etc.

**Comment by Licho1** [comment]
users cannot upload maps and images are checked for being images afaik.

**Comment by mojjj** [comment]
has something changed in BB-Code replacement? back in the day when i added the [video] tag, there was no sanitation of user-input.

**Comment by shaun0x00** [comment]
I see absolutely no change justifying why this issue was closed.
@Licho1, it is called a mitigation technique because "AFAIK" isn't enough if you are serious about keeping your users secure.

I suppose the best use of my time is to just wait for this to be exploited and then point out that ZK team had been warned years before.

**Comment by sprunk** [comment]
>users cannot upload maps

Users can upload maps to Springfiles and ZK infra distributes those maps.

**Comment by shaun0x00** [comment]
@sprunk I'm not sure this will help him realize... this will only cause fingerpointing and justify starting development of a Springfiles alternative (with its own set of home-grown problems).
GIFar is the classic example, but I see him invest time in explaining how/why it may no longer be a valid exploit vector instead of considering that there are a lot of unknowns, hence the need for mitiigation.

**Comment by Licho1** [comment]
I think we can block non-supported maps then. This will cause admins to verify every map.
As for "GIFar" you do realize you cannot just do it with randomly uploaded file if the server and code expects it is gif right? 
Site already sanitizes some stuff by resizing images.

Furthermore, sanitization itself can make the server vulnerable.. see for example:
http://stackoverflow.com/questions/10196351/image-sanitization-library

Action would be needed with generic file upload, but since it is of fixed image mime type, and is only served by this fixed mime type, it would need some really horrible 0-day bug in browser to do something evil.

So if you find better way than resizing the image, make a ticket.

**Comment by shaun0x00** [comment]
This is funny, in a sad kind of way.

This ticket was not specifically about images. The GIFar example was just an attempt at triggering thought, though as expected, it didn't work.

As explained time and again, I'll no longer open tickets. In ZK project, it is perfectly acceptable not to learn about best practices and then proclaim "AFAIK".

Enjoy your release.

Yours faithfully, Dunning & Kruger.
