### ISSUE TITLE
Dedicated server can't be retrieved from spring builds anymore

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2391]
Spring maintenance has a new folder structure.

Dedi is now in `C:\projekty\springie_spring\engine\win32\104.0.1-616-g52f5f2b\spring-{maintenance}104.0.1-616-g52f5f2b_win32` instead of `C:\projekty\springie_spring\engine\win32\104.0.1-567-gc484c10`

**Comment by DeinFreund** [comment]
Repack it manually.

**Comment by Histidine91** [comment]
Did someone upload the 616 engine for win32 using the portable archive instead of the minimal-portable one? The former uses the changed folder structure observed above, the latter does not.

Basically, no change should be currently necessary if the correct archives are uploaded (always use minimal-portable).

**Comment by sprunk** [comment]
Would be good to add a "must be minimal-portable" red bold text on the upload button or something

**Comment by DeinFreund** [comment]
I did not know that. I've repacked the normal archive instead for 621.

**Comment by Histidine91** [comment]
Added bold (but not red) message to engine page.
