### ISSUE TITLE
Don't count custom battles with unbalanced teams for rating.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2409]

**Comment by Licho1** [comment]
Why? Why not disabling it in custom rather.. or in any place where modoptions are used etc..
"Unbalanced" is not relevant imo.

**Comment by DeinFreund** [comment]
We should still try to include as many battles as possible, to increase rating accuracy. Custom battles with equal numbers of players can be rated just fine.

I'm not sure about modoptions, but it probably makes sense not to rate them. Although in that case, noelo specifically exists as an option which we'd take away.

**Comment by sprunk** [comment]
I think teams with unequal playercounts should be counted as long as starting resources are kept same (eg. if in 2v5 the smaller team has 5 comms). However this is not always the case at the moment because people can only get 2 comms each (1 own + 1 extra, eg. in a 2v5 the smaller team has 4 comms).

**Comment by DeinFreund** [comment]
Custom battles don't even give extra coms in 2v3, which is why I don't think they can be considered fair battles.
