### ISSUE TITLE
Springie !setengine bugged / password protected games setengine

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#243]
Exploit reports setengine is bugged for them (running zkl on linux).

Secondly, password protected games with setengine does not auto-rejoin the player.

**Comment by blah1** [comment]
In case nobody realized it yet, this is caused by Springiee using a Global variable for "CurrentEngine" (or whatever it's called). Steps to verify:
1. PM to any Springiee host: !spawn title=Room A,mod=zk:stable
2. Enter Room A and give the command: !setengine 88.0 (or whatever you want)
3. Springiee## replies with "[3:33 PM]  * Springiee6 Preparing engine change to 88.0
[3:33 PM]  * Springiee6 rehosting to engine version 88.0" and rehosts the room
(you can rejoin the room, I didn't bother for this test)
4. PM to any Springiee host: !spawn title=Room B,mod=zk:stable
5. Enter Room B and give the same command as before: !setengine 88.0
6. Springiee## replies with "[3:34 PM]  * Springiee14 Preparing engine change to 88.0" and doesn't change the engine

The bug is that the engine in use is shared between hosts, so if host A changes to 91.0, host B thinks that it already has 91.0 even though it didn't change

**Comment by xponen** [comment]
nice theory! 
i'm checking Springie code in case I can see this global var
