### ISSUE TITLE
MM map veto design

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2444]
Players should be able to pick which MM maps they do not play on. Here are the components:
- Every player should have 6 DB keys called something like mapban1 through mapban6.
- Players can set these values by entering strings (with autocomplete, as seen here http://zero-k.info/Battles) into six text boxes in a small dedicated map ban page which is accessible via a link on the homepage.
- Every match size should have a number of map bans. Reasonable values for the current pool are 6 for 1v1, 3 for 2v2, 3 for 3v3 and 2 for 4v4.
- When a MM game is created, the map is chosen from the pool of maps created by banning the first X maps selected by both players to be banned. X varies depending on game size.

The backend should not care whether the maps banned by a player are MM maps, to avoid fancy checking or validation when the MM pool is updated. The UI should only consider MM maps for its autocomplete.

See: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1552

**Comment by Anarchid** [comment]
> Every player should have 6 DB keys called something like mapban1 through mapban6.

IMO: separate table, something like `AccountMapBans` with fields `AccountID`, `BannedMapResourceID`.

**Comment by Licho1** [comment]
Yeah you dont do 'MapBan1, MapBan2, MapBan3" thats bad design. But i think this is just a description of the concept. 
Also imo its a pointless feature. It's a very niche feature for a very niche way to play the game.

**Comment by GoogleFrog** [comment]
Sure, separate table.

@Licho1 it's a very important feature for the MM because many people don't like some maps. This is my experience from talking to just about anyone about updating the MM pool. I think the MM would see a noticeable increase in activity if people were able to queue with the surety that they won't be served the maps they most dislike.

**Comment by GoogleFrog** [comment]
Any update?

**Comment by DeinFreund** [comment]
I'd like an infra stable before doing any further changes to the MM. There is already a major rework for autohosts as well as some changes to the MM in the pipeline. For that we'll need to test and deploy:

https://github.com/ZeroK-RTS/Chobby/issues/654
https://github.com/ZeroK-RTS/Chobby/issues/650

**Comment by Legomenon-gh** [comment]
I have MM running locally and intend to take a stab at implementing this since I'd very much like to make the MM map pool more configurable by users.

The last comment above by @DeinFreund implies autohosting is being reworked. Is this still current, and how much of a blocker is it? (e.g. how much of a merge conflict would it end up into in the future?)

**Comment by GoogleFrog** [comment]
That comment is not relevant as it is from 2018 and an infra stable has been made since then. Autohosting has nothing to do with the matchmaker, except for a system DF added that is defunct (as far as I know). In any case, no work is being done on it.

**Comment by Legomenon-gh** [comment]
Thanks, I saw the comment was from 2018 but wanted to double check since the two issues below it still being open.

Implementation looks fairly straightforward but I have a question on this requirement: `When a MM game is created, the map is chosen from the pool of maps created by banning the first X maps selected by both players to be banned. X varies depending on game size.`

It seems strange to me that banning a map has no effect unless the other player also bans it, 
especially for team games. Should a veto work as a weight to the random pick instead so a single vote has an impact? (For each veto, reduce the probability of that map being picked by %Y / number of players. The simplest case in 1v1 is reduce the probability by 50% if one player vetoes the map, and removes it completely if both players veto it)

It would be simple to add the ability to like maps so they're more likely to be picked in MM, but I'm assuming this isn't worth adding right now (custom games can serve that purpose already, and this would make the map preference UI get pretty complicated). Let me know if you think being able to like maps would actually be desirable.

**Comment by GoogleFrog** [comment]
> When a MM game is created, the map is chosen from the pool of maps created by banning the first X maps selected by both players to be banned. X varies depending on game size.

This is just ambiguous wording. Take the union of the first X maps of each player and ban that set. Bans should not mess with the probabilities either, once something is banned the player should never see it.

Here is how it could be fixed:

> When a MM game is created, the map is chosen from the pool of maps created by banning the first X maps selected, for each player, to be banned. X varies depending on game size.

**Comment by Legomenon-gh** [comment]
Ha, both can be an intersection or a union :D Simple enough now that's cleared up!

**Comment by sprunk** [comment]
#2682
