### ISSUE TITLE
privacy hell - 5 donators payment details publicly disclosed

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#259]
It has been indexed by google
It shows how responsible zk is with players and donators personal data...

How will you handle this?
Make a public announcement and warn the 5 donators that their details are now publicly known.

**Comment by knorker** [comment]
> They will be notified. To minizime harm this ticket will now be deleted

loled

**Comment by KingRaptor** [comment]
https://github.com/isaacs/github/issues/253

**Comment by shaun0x00** [comment]
This is nearly 2 years old and closed. Why bother now?
The rest of the thread is still valid
1) you still hide who you are. Trying to avoid liability in case bad stuff (like that) happens?
2) you still do not provide a way to report security vulnerabilities and would prefer to hide previous problems?
3) you now collect and store even more information about the players and admins, which is totally irresponsible given your security track record
4) you still regularly push files with passwords or private info to repo

**Comment by knorker** [comment]
> isaacs/github#253
That link is about deleting a issue completly.

What needed to be done here is deleting a file (and its history) completly. As in the link I linked in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/259#issuecomment-64677396

Deleting the issue/ticket archives nothing.

**Comment by knorker** [comment]
also lol that by linking to that irrelevant issue it is now listed as reference there where hundreds of peoplers see it

**Comment by shaun0x00** [comment]
Can't help.
The "dev team" may consider abandonning github.
After all, it worked in making all googlecode's issues disappear.
For example, I see no warning/issue that the lobby self-updates itself by downloading some random exe from an unsecured server... and proceeding without any check. This was in previous bugtracker.
So they can hide stuff. Though at some point it will resurface and bite them... because the code is all that matters.

**Comment by KingRaptor** [comment]
I can add contact page with team email at the very least. May also kill the commit history with BFG.

@knorker: If your point was that the file history needs scrubbing from repo, don't quote "this ticket will now be deleted" and reply with "loled"

>3) you now collect and store even more information about the players and admins, which is totally irresponsible given your security track record

The only added data collection in the past year (or three) I can think of is PMs, which was reverted (and was never requested by any admin I've talked to to begin with).

>4) you still regularly push files with passwords or private info to repo

Where? (mail to team -at- zero-k.info if you don't want to post here)

> The "dev team" may consider abandonning github.
After all, it worked in making all googlecode's issues disappear.

Once you stop _literally making shit up_ about our motives and intentions we'll know we're making progress.

**Comment by shaun0x00** [comment]
Facts: when you moved from googlecode to github, you didn't import the known issues. Some of those problems are still in the code but you lost track of them.
Not making shit up.

My suggestion that you may consider the option of moving away from github was just sarcasm to highlight repeated bad management decisions and what kind of consequence it has on code currently deployed (on server side and on players machines). I used the example of the selfupdater to illustrate that.

I feel no urge to waste more time now to prove anything. It doesn't lead to beneficial changes for players anyway, or at an exorbitant price. Remember how costly it was to debunk regex parsing, password in cookies, broken installer, broken network code, etc etc etc. Not interested in repeating that, given the outcome, especially for bugs that have been discussed and documented already, but due to careless management, are now "gone" from books.

So about progress being made, when you'll say "this code is release worthy, we release it on Steam", then I may bother having a look. In the meantime, watching the cumulative issue count hovering just below 250 and seeing players reports is enough to infer that you are not there yet and that I shouldn't even care.

Just consider that I'm making shit up and do your release... arguing before that makes no sense.

**Comment by knorker** [comment]
> @knorker: If your point was that the file history needs scrubbing from repo, don't quote "this ticket will now be deleted" and reply with "loled"

I had already written my point: Delete file & its history, and linked how to do it.
Then Licho announced to take a different (ineffective) action. And then did not even do _that_.
So I bump it with "lol."
And also lol because it is funny.



>  PMs, which was reverted (and was never requested by any admin I've talked to to begin with

**Comment by KingRaptor** [comment]
>Facts: when you moved from googlecode to github, you didn't import the known issues. Some of those problems are still in the code but you lost track of them.
Not making shit up.

>My suggestion that you may consider the option of moving away from github was just sarcasm to highlight repeated bad management decisions and what kind of consequence it has on code currently deployed (on server side and on players machines).

Your previous post clearly insinuates that we moved away from Google Code with the deliberate intent of covering up issues, and that we might do the same with Github. Your pretense otherwise, and of not understanding the charge, reflects tone-deafness at best or dishonesty at worst.

If you have any interest whatsoever in things getting better (or at least not getting worse), leave the sarcastic insults out of Github comments. But I see that you have specifically stated you don't:

>I feel no urge to waste more time now to prove anything. It doesn't lead to beneficial changes for players anyway, or at an exorbitant price. Remember how costly it was to debunk regex parsing, password in cookies, broken installer, broken network code, etc etc etc. Not interested in repeating that, given the outcome, especially for bugs that have been discussed and documented already, but due to careless management, are now "gone" from books.

>So about progress being made, when you'll say "this code is release worthy, we release it on Steam", then I may bother having a look. In the meantime, watching the cumulative issue count hovering just below 250 and seeing players reports is enough to infer that you are not there yet and that I shouldn't even care.

If you don't want to help, fine, don't. Don't say issues are there and _then_ get all coy (and snarky) about it when _someone who actually wants to fix stuff_ asks for details. For that matter, don't bring up issues if you already know you're not going to provide details when asked. That just wastes my time and my health.

**Comment by knorker** [comment]
> insinuates that we moved away from Google Code with the deliberate intent of covering up issues, 

No, zK would never be capable of such planned action. Instead you waste players & reporters time by losing track of bugreports by bad orginzation.

> Don't say issues are there and then get all coy (and snarky) about it when someone who actually wants to fix stuff asks for details.

I never see much asking for details.
In the last years I have only seen constant bragging how great the game/lobby/whatever is, and how it would be perfect to release on steam in this state. http://zero-k.info/Forum/Thread/9877?postID=149956#149956 and similiar.
Which is totally ignoring the reported issues in bugtracker plus countless more reports in forum that get lost in forum and chat.
I have never seen devs being so blind to status of project. It would be their own stupid problem, if that ignorance and greed had not fucked up springs future as a whole.

> when someone who actually wants to fix stuff

Like this report?

**Comment by KingRaptor** [comment]
@knorker: I'm sure you think Licho having a really wrong view of lobby state 7 months ago (or any other such incident you can name) is relevant to a supposed issue reporter failing to give a person-who-is-not-Licho useful information in the here and now, but it's not. It is also not helping the exact thing you're complaining about with issues being ignored.

Bad things going unfixed in the past is not an excuse to troll on the (however few) times someone actually tries to fix them.

>Like this report?

Yes, like this report. We still haven't decided whether altering 2-3 years of commit history in all the branches to hide five email addresses and donation records is worthwhile (especially when none of them have requested such an action to my knowledge), but if more sensitive information (like passwords) has been put in repo more recently, _I_ want that fixed.

**Comment by knorker** [comment]
>  I'm sure you think Licho having a really wrong view of lobby state 7 months ago (or any other such incident you can name) 

It is not single "incidents", it is ongoing process since the the last 2, 3 years.
The whole steamdream and every major decision is built on wrong judgement.

When the project-leaders are so blind view on issues, that is relevant to the motivation of players to report bugs. zK had been given useful details and bug reports by large motivated playerbase for very long time. Reporting errors takes effort, and devs wasted (continue to) that.

> is relevant to a supposed issue reporter failing to give a person-who-is-not-Licho useful information in the here and now, but it's not. 

You have the file, you know what the problem with the file is, you had been given a way how to deal with it. You do not need further information.

>  if more sensitive information

lets discuss whether email and RL-names are sensitive information or not.

**Comment by KingRaptor** [comment]
>When the project-leaders have so blind view on issues, that is relevant to the motivation of players to report bugs. [...] Reporting errors takes effort, and devs wasted (continue to) that.

Except the person in question here is perfectly happy to (technically) report a bug, but when asked for details makes two lengthy paragraphs talking about how shitty the devs are instead. Could not report at all, or make abbreviated report and not respond when asked, instead of doing that. (That's assuming the purpose of the exercise is anything other than opportunistic insulting of devs and proving how right and wise oneself is.)

>You have the file, you know what the problem with the file is, you had been given a way how to deal with it. You do not need further information.

The "further information" was in reference to

>3) you now collect and store even more information about the players and admins, which is totally irresponsible given your security track record

>4) you still regularly push files with passwords or private info to repo

I do not believe this was ambiguous given the quote chain involved.

>lets discuss whether email and RL-names are sensitive information or not.

Two of the people affected already disclose their real name either here or on SpringRTS forum (as do I), and one of those also has a publicly visible email in the same place. If any of the five felt the information was private enough to require retroactive scrubbing from repo, I have not heard it. (No, this is not to say that the leak was in any way desirable.)

**Comment by KingRaptor** [comment]
I've successfully test-pushed a BFG-scrubbed repo to my fork. Some origin branches are still being worked on so I'll probably do the process again once the kill-springie branch gets merged.

**Comment by knorker** [comment]
> Except the person in question here is perfectly happy to (technically) report a bug, but when asked for details makes two lengthy paragraphs talking about how shitty the devs are instead. Could not report at all, or make abbreviated report and not respond when asked, instead of doing that. (That's assuming the purpose of the exercise is anything other than opportunistic insulting of devs and proving how right and wise oneself is.)

'Two lengthy paragraphs' is nothing compared to constant bragging and silly promises of zK devs in last years. Always talking about how their mod is superior to other mods, not even hesitating to fuck up spring (playerbase etc) just so they can say 'zK is on steam'. How arrogant and greedy does one have to be to fuck up years of spring modding, for a tiny chance of exposure?
And then they did not even archive anything, because none of the stuff they praised so much works (or was even tested or in existance)

> I've successfully test-pushed a BFG-scrubbed repo to my fork.

good, two years after the issue had been closed someone begins to act.

**Comment by shaun0x00** [comment]
lol

The arrogance and incompetence of zk developpers has created hostility around it and isolated itself. No longer interested in helping alleviate such consequences. Is it hard to understand that when your actions are really odious, you attract hostility and it becomes harder to get help and get sarcasm instead?

@KingRaptor you never look back anyway, don't you?
You never analyzed retrospectively, all the dramas there has been everytime there has been report of problems that you refused to acknowledge or that you blamed on external factors. All the shit you said that was wrong, but took months/years to be acknowledged, to finally never credit those who did the job of solving difficult problems. This is why I was using the term "costly" above. Of course I could also have referred to the "donation" money that is handled like private money, and server paid with donations like a private server...

@KingRaptor  as you were perfectly aware of all the details regarding previous bug report/drama but again showed unwillingness to contradict @Licho1, you are definitely not part of the solution.

Regarding my attempts to help the project, read here : http://zero-k.info/Forum/Thread/9877

To get an idea of how long this has been going on: 
http://zero-k.info/Forum/Thread/8731?postID=94314#94314
http://zero-k.info/Forum/Thread/8731?postID=94343#94343

**Comment by KingRaptor** [comment]
Shorter version: "it's okay for me to shit up a Github comment thread because ZK devs are idiots who didn't listen when I tried being nice"

"even though my new strategy is working no better and is making things worse in general"

"even though 'two wrongs make a right' is a super well known fallacy"

"even though I know full well my current behaviour is impeding solutions to the very thing I'm using to justify my actions"

I have had more than enough of the stress from dealing with you. This conversation is over.
