### ISSUE TITLE
Malformed circuit config

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2596]
https://github.com/ZeroK-RTS/CrashReports/issues/22768

**Comment by Cat-Lady** [comment]
It looks like some ZK builds interpret ':' inside comment as something to parse (while other, for whatever reason, know that anything starting with comment marks is not to be parsed up to end of line) - line 28 contains

"// FIXME: last 2 aren't superweapons"

...which makes script fail on following line (29).

The issue was *not* introduced during my latest edits to AI - the comment was there before, exactly where it is now - nevertheless, I've moved the comment outside of line ending, and formatted it in a way that it doesn't contain the ':' character. Hope it fixes the issue - I don't have testing machine that was affected by the parsing differences.

**Comment by Cat-Lady** [comment]
Seemingly fixed in:
https://github.com/ZeroK-RTS/Chobby/pull/699

It seems that some builds of ZK interpret things following '//' (comment mark) as possible markers to resume interpreting, while others not. I have no idea what causes the difference, but I've tested various .json interpreters, and indeed, some of the treat anything past '//' as comment to the end of the line, while others do not.

This commit aims to fix the issue at hand - hoever, in my opinion all our .json files should get scrutinized for comments formating and sanitized, OR reason for the difference in interpreting between ZK builds get discovered and ensured that all know what to do with comment lines. Otherwise, there be possible Dragons in the future.

**Comment by Cat-Lady** [comment]
Side note - this issue should be moved from 'Zero-K-Infrastructure' section, to 'Chobby' section. Otherwise, referencing pull requests/issue and its fix doesn't work.

**Comment by Anarchid** [comment]
This is a duplicate and it is in the wrong repository (neither Chobby nor Circuit).

**Comment by GoogleFrog** [comment]
The fact that we only received one bug report about this indicates that infra may be downloading old or corrupted files. The issue occurred on windows and there is only one windows 'build' in the important sense.

**Comment by Cat-Lady** [comment]
It is possible, but I find it rather "suspicious" that the line mentioned in the "malformed" error - line 29 - is exactly the same as the line that becomes "corrupted" in .json interpreter sense (due to the comments in previous line). Might be coincidence.

Pity, that infolog doesn't contain version number (or hash) for those configs.

**Comment by rlcevg** [comment]
```[f=-000001] Skirmish AI <Circuit Normal-stable>: Malformed config format! (build_chain.json)
* Line 29, Column 71
  Missing ',' or ']' in array declaration
```
missing comma in line 29, that is
```
		"weight": [ 0.1,         0.2,          0.3,               0.1       0.3],
```

**Comment by Cat-Lady** [comment]
*facepalm* Fixed in:
https://github.com/ZeroK-RTS/Chobby/pull/699

Thank you for spotting what we all were unable to spot :)
