### ISSUE TITLE
Remove dependence on Spring infrastructure

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2685]
The state of Spring development has been declining for a while so it is reasonable to have replacements ready in case the infrastructure breaks. As far as I am aware we depend on Springfiles and rapid for builds and for map releases.

**Comment by Licho1** [comment]
Ok ...
Should not be very hard. We had at one point, provided rapid for rest of spring since it was invented for CA originally. As far as the maps go, we have the tools to extract metadata so should not be a big deal. Problem might be hosting but we do host the full mirror for maps anyway even right now.

**Comment by Licho1** [comment]
Maps are now independent. Rapid stuff deserves another ticket if needed to be replaced.
