### ISSUE TITLE
Consider exposing WHR changes to non-admins

### ISSUE THREAD

**Issue by Legomenon-gh** [ZeroK-RTS/Zero-K-Infrastructure#2800]
The BattleDetail view displays WHR changes for battles for admins: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/Views/Battles/BattleDetail.cshtml#L144

This might be interesting information to show to users too to make the ranking system appear a little less opaque. Displaying this information for the user's battles is probably enough (I don't think there's a lot of value in seeing WHR changes everywhere).

**Comment by DeinFreund** [comment]
Note that this information is already sent to every user in the format of a BattleDebriefing message.

**Comment by sprunk** [comment]
I think the reason this is hidden is that it would confuse people because it shows the change as happened at the time of the battle and not the actual change afterwards. For example if you lost 50 elo by losing to a godde smurf but then this was adjusted to 0.3 once the system realized who this is, the website will still say -50. Battle debriefings are more okay in this regard because you can't just go back to them after a month and say "ew, totally unfair".

**Comment by Legomenon-gh** [comment]
Yeah, BattleDebriefing does most of what I'd like, and knowing it exists pointed me in the direction of https://github.com/ZeroK-RTS/Chobby/issues/678 for background information, so closing this issue
