### ISSUE TITLE
Make Epic downloadable

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2838]
Looking at the replay list this map seems some use and it worked when I last tried.

[Epic.zip](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/7149233/Epic.zip)

**Comment by Licho1** [comment]
Is the standard upload to zk map thing not working?

**Comment by Licho1** [comment]
There is a an option to upload map on maps on zk site
![image](https://user-images.githubusercontent.com/3185783/133218888-0a31e196-8bee-450d-a588-ac11761bbb32.png)
It will "unitsync" the file, reading the metadata and create entry in the system. If the internal name is different it will be a new entry. 
Otherwise it will add a download file mirror.

**Comment by Arch-Shaman** [comment]
![image](https://user-images.githubusercontent.com/48730089/147492020-77d67d4c-283d-4c76-9d51-8d3f775b12fa.png)
