### ISSUE TITLE
clarification needed

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#355]
please clarify if you want be part of the spring community or not.

https://github.com/spring/uberserver/issues/129

imo part of community  = share work / infrastructure / user database(s)

makes me think Zero-K doesn't want to be part of the spring community.

(this is no "official" question, just my personal opinion/question)

**Comment by Licho1** [comment]
I can only speak for myself too, but imo ZK definitely is part of spring community and wants to continue be so, thats why I proposed the federation/clustering protocol.
Even if ZK decides to have own server for lobby, I would maintain common channels like #sy shared between them even if battles could not be.

I mainly care about players who I think are the community. Do you want to be part of spring community and work for its benefit? Lots of stuff is being done that does not benefit the actual community - the players. Like insisting on "clean" implementation of forcejoin despite its real world shortcomings etc..
It's also annoying to be on the receiving end of changes outside our control/review, like the recent patch which accidentally disabled quickmatch at the same time I announced ZK is temporarily moving to "quickmatch only", resulting in a rage and lost confidence of players in the system...

Splitting servers will undeniable do a harm to community, though I believe it's needed for steam -> future hopefully bigger community.

ZK might also need to fork engine in the future but thats unlikely to be done as fork, rather as branch on main repo.

**Comment by abma** [comment]
>  Like insisting on "clean" implementation of forcejoin despite its real world shortcomings etc..

feel free to create a clean implementation. you didn't contribute to lobby protocol / lobby server. you seem to not care about a standard, so other games could use it as well.

>  like the recent patch which accidentally disabled quickmatch at the same time I announced ZK is temporarily moving to ...

when stuff is changed, stuff can break. it was broken for ~6 hours which is nothing in comparison to other breakages / outages.

> Splitting servers will undeniable do a harm to community, though I believe it's needed for steam -> future hopefully bigger community.

as you did it, both codebases have to be maintained in seperate: work has to be done twice / code can't be shared. also you removed the two most major contributions recently made to uberserver.

> ZK might also need to fork engine in the future but thats unlikely to be done as fork, rather as branch on main repo.

imo this will make both projects die. see glest/megaglest.

**Comment by abma** [comment]
unsuscribed here. you (ALL zero-k-devs) have to decide.

**Comment by xponen** [comment]
I will vote for cooperation & merging of works. 

We won't have enough man-hour to control and code everything. 

The success we had today is not entirely our own work. We will never able to top it (better it) if we alienate all the unknown contributors.

**Comment by GoogleFrog** [comment]
I vote for merging but do not know much detail about the situation. I know more about the engine situation and would not fork the engine.

The impression I got of lobby development was that it is impossible (politically) to change the protocol to let it do things that we want it to do. Also the lobby seems to suffer from unexpected downtime and messing about with features that are important for the running of ZK (such as removing forcejoin while trying to make a matchmaker work with everyone).

**Comment by Licho1** [comment]
Clarify what do you mean by "merging" and what work you yourself intend to do for that goal.

**Comment by Anarchid** [comment]
I'd prefer to have ZK-uber changes to be inflicted onto "original" uber code tree whenever not too destructive if this counts for anything.

ZKDB authentication and other things can be implemented as hooks/plugins/config options/whatever. I understand this adds some extra work.

I can write python, so i can contribute towards this.

**Comment by Licho1** [comment]
I intend to secure DB and login commands. 
To secure register needs SSL or KlootSSL but that adds always on encryption which is madness with the aim of 7k players (to encrypt all with AES is a waste) AND site uses http so site will be weak link until its switched to https.
So my plan is simple:
1) add warning to register to tell people to use random unsecure pw
2) properly store data in ZK db (salted hashes)
3) secure lobby protocol login (trivial, optional addition wont break old lobbies)
4) *later/low priority* swap site to https, use register through site service with https providing MITM security.

Alternative to it would be using SSL for lobby server, which is trivial both in python and C# and much preferable imo to KlootSSL but also less desirable because WTF we are not NSA and I don't want to burn clock cycles on encrypting sfireman rage.

**Comment by Licho1** [comment]
Btw also if yo didn't move lobby server to other server, I would be doing this with the official one..
(In less dramatic/optimal way of course).

**Comment by Kaylewt** [comment]
To secure register needs ...SSL but that adds always on encryption

You are misinformed: https://github.com/spring/uberserver/blob/master/DataHandler.py#L36 versus https://github.com/spring/uberserver/blob/master/DataHandler.py#L37

**Comment by Licho1** [comment]
Ok but for ZK its still odd to use that for registration, because ZK users use identical login to site/forum which is (like springrts.com) http.. so the weakest link will just move to site login..

Besides Abma insisted on using always on encryption for "federation" which means encrypting all incoming traffic...
