### ISSUE TITLE
questions related to lobby server fork/split

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#382]
1 do you plan to host the rapid repo at your server?

if not:
1.1 when will https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/198 be fixed?

this is a major bug, as it causes a LOT of traffic for springrts.com / load peaks.

1.2 will http://repos.springrts.com/zkmanual/ be used / is it used at all?

1.3 please don't forget to fix zero-k lobby https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/301 (which is a preparation of 1.1.)

2 this exceptions on springrts.com still exists for zero-k only: buildbot creates .zip files, i.e. http://springrts.com/dl/buildbot/default/master/98.0/win32/spring_98.0_minimal-portable+dedicated.zip

are/will they be still used or can they be removed? (creating the zip file) .7z files with same contents exist. -> they are a waste of bandwith / disk space.

3 are you still hosting non-zk games on zk-lobby server? (i.e. SWIW is gone from the official server now)

**Comment by Licho1** [comment]
1) i do plan to host repo server, but not master, just ZK. I will let you know when that happens. I need to control build process including rapid step to create steam package with lobby and rapid files, thats the main reason. But it should be part of standard rapid infrastructure, just content files hosted on ZK machine later. 

1.1) it will be fixed, i plan to move that part to plasma so that only one server asks. It's a bigger rewrite and im busy fixing other bugs now but im aware of your deadline.

1.2) it is used directly by ZK site atm, but not updated correctly (it needs manual run each time we release game version) - it's also reason why i want to move it to ZK server so that we can run/maintain it reliably. Will notify when its moved.

1.3) this will also be applied

2) these are and will be used, pelase keep them

3) i will host any games on any server if someone asks me to (that includes springrts.com, though i believe that spads is superior for non ZK hosting). Springie still has configuration files for all those hosts they are just offline atm, if you want to enable some tell me which and where and i will do so.

**Comment by abma** [comment]
ok, thanks for the info. would be nice to have some hint when its done.

i hope the date for 1.3 is reasonable, if not please poke me (but this really worries me, as the apache access.log for i.e. http://zk.repo.springrts.com/ is ~22 MB each day! (and there exists ~10 repos => 220 MB of logs, just for the accesses to the repo)

**Comment by abma** [comment]
as note: would be nice if 2. could be fixed...
