### ISSUE TITLE
Cannot connect to springie with dev engine randomly

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#468]
Sometimes when trying to start a game on Springie with dev engine I have "Connecting to server" in spring and an eventual timeout. Clicking "rejoin" just causes another timeout. Leaving and reentering the battle room then clicking "rejoin" tends to fix the issue.

http://pastebin.com/pBUHG1QX

**Comment by Licho1** [comment]
When it happens check springie infolog in c:\projekty\springie_spring_test

**Comment by Orfelius** [comment]
I had the same issue yesterday GoogleFrog. Interesting thing is that, when it fails in Bleeding Edge, it Beta room doesn't time out.

**Comment by xponen** [comment]
This could ALSO be caused by ZKL failing to change to Spring dev version. 

Someone should try to check whether the correct Spring version is being launched (go to taskmanager, check the folder name of the spring.exe which stalled)
This can help to figure out whether its Springie issue or ZKL issure..

**Comment by db81** [comment]
Still happens?

**Comment by GoogleFrog** [comment]
I would not know. I have not tried to run dev engine on springie recently.

**Comment by Licho1** [comment]
fixed
