### ISSUE TITLE
Getting the Swap Servers Button

### ISSUE THREAD

**Issue by Falcon7617** [ZeroK-RTS/Zero-K-Infrastructure#484]
I cannot switch to a different server as the button is not there, nor does the link work, I need help on how to get these so I can play again.

**Comment by Orfelius** [comment]
Look up news. ZeroK Lobby does not support protocol with uberserver (the spring server with other games) anymore because it has implemented a new protocol and is being hosted on another server. Seriously you even get a popup when you start ZKL that tells you that.
You can play other spring games by downloading other lobby like Spring Lobby or Web Lobby but ZKL is no longer compatible with old lobby.
That is all and I wish you all the best.
(please close the issue?)
