### ISSUE TITLE
Game factions for other Spring games

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#603]
Recently 2 folks were trying to play NOTA on our server (for some reason) and have discovered that ZKL does not support changing a game faction anymore as in for example CORE or ARM.
In my opinion if Zero-K server shall allow non-ZK games to be hosted then it also should support all of the Spring engine features even these which are not being used by ZK.

Edit: Quoting Licho "There is no plan to restrict non-ZK games. The checkbox "show only official games" stays and thats it. If there are other games hosted on the same server, they will be downloadable and joinable."
Well that is acheived already but then if they are allowed then why they are not fully functional?

**Comment by sprunk** [comment]
just because they aren't specifically restricted does not mean anybody is going to put the work to implement stuff just because 2 people can't be arsed to use old uberserver

**Comment by Orfelius** [comment]
So I told them!
But inconsitency is still an issue and I can understand this being a low priority work since there is so much more stuff left to do in infra.

**Comment by knorker** [comment]
> (for some reason)

The mods are there to be selected: that is reason enough to cause players to (want to) try them.

> I can understand this being a low priority work since there is so much more stuff left to do in infra.

That is understandable.
But I find how it is/was communicated to players dishonest:
zK-lobby was often recommended/advertised to non-zk players in chat and forums with the arguement that it supports all mods.
Imo that was a bit dishonest because mods might be "downloadable" and "joinable", maybe even "playable" - but important features have always been missing from zK lobby/infra as long I can remember.

-factions selector
-color selector
-replays for non-zK games: code.google.com/p/zero-k/issues/detail?id=1226&q=replays
-missions for non-zK games
-map selection of non-zK maps
-mods dowloads https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/611
-default-joining chat channels
-...

**Comment by xponen** [comment]
ZKL had
-faction selector
-colour selector 
but server protocol doesn't support this

**Comment by Licho1** [comment]
Could we perphaps get some gadget to let people select faction ingame and link it to all mods?

**Comment by knorker** [comment]
From technical side: yes, of course.
But that misses the point, anything can be ingame: team colors, handicap, team balance, modoptions, mapoptions, ...
Spring/lobby/modding documentation describes how faction-selection works, so if it does not exist then the implentation is incomplete. Maybe with zeroK's new lobby protocol things are different now.

**Comment by Licho1** [comment]
Yeah I skipped it from protocol i can of course readd it but problem is layout for lobby itself. Its hard to design it with empty space for this selector.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
