### ISSUE TITLE
ZKI cannot into new maps

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#622]
1) ZKL fails to download maps which are available through Rapid but not yet known by ZKI (because no games were played on them).
- issue in private to your nearest Springie: `!spawn mod=zk:stable,map=AstroTurf v2_3`
- join the created room
- observe download fail in ZKL
- obtain rSWL or flobby; try the same
- observe download work for these lobbies.

2) ZKL fails to find manually downloaded maps.
- [download](http://api.springfiles.com/files/maps/astroturf_v2_3.sd7) astroturf 2_3 manually and place into your maps folder
- spawn the host as above using '!spawn mod=zk:stable,map=AstroTurf v2_3'
- join the resulting host
- you will still be unsynced, and restarting ZKL will not help 

3) Springie fails to record games played on such maps:
```
4:25:39 PM	*	Nightwatch 14.5.2015 15:25:36 Error System.InvalidOperationException: Sequence contains no elements
4:25:39 PM	*	Nightwatch at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
4:25:39 PM	*	Nightwatch at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__3[TResult](IEnumerable`1 sequence)
4:25:39 PM	*	Nightwatch at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
4:25:40 PM	*	Nightwatch at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
4:25:40 PM	*	Nightwatch at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
4:25:40 PM	*	Nightwatch at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
4:25:40 PM	*	Nightwatch at ZeroKWeb.SpringieInterface.BattleResultHandler.SubmitSpringBattleResult(BattleContext context, String password, BattleResult result, List`1 players, List`1 extraData)
```

These together mean that adding new maps is impossible.

**Comment by lhog** [comment]
From ZKL log:

'14.05.2015 16:29:25: Unable to deserialize map AstroTurf v2_3 from the server: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at ZkData.MetaDataCache.GetMap(String mapName, MapCallback callback, Action`1 errorCallback)'

**Comment by xponen** [comment]
ZKL will register this map in Windows as soon as it's downloaded but weren't able to do this in Linux because it doesn't have obvious way to import Spring DLL in same way it was coded for Windows.

**Comment by lhog** [comment]
@xponen, I'm on windows. and this was exactly same map I uploaded into springfiles.

**Comment by xponen** [comment]
my ZKL have registered AstroTurf v2_3, we should check now @lhog

**Comment by Anarchid** [comment]
Apparently this is resolved by enabling "Enable Unitsync Dialog" or something.

**Comment by xponen** [comment]
That option not mandatory unless its coded wrongly! O_O

**Comment by lhog** [comment]
Actually '"Enable Unitsync Dialog" or something' doesn't solve the issue. Here are two new maps with the same story (uploaded to springfiles and visible through http://api.springfiles.com, but not seen in http://zero-k.info/Maps/):

http://springfiles.com/spring/spring-maps/apophis
http://springfiles.com/spring/spring-maps/tma-0-0

**Comment by sprunk** [comment]
Apparently Windows will recognize a map when you *paste* it into the maps folder but *not* when you *copy* (or the other way around).

**Comment by shaun0x00** [comment]
[9:13 PM]  * Nightwatch 14.5.2015 21:13:56 Warning Error getting mirros from springfiles: System.Net.WebException: The operation has timed out
[9:13 PM]  * Nightwatch    at System.Net.HttpWebRequest.GetResponse()
[9:13 PM]  * Nightwatch    at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse(WebRequest request)
[9:13 PM]  * Nightwatch    at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
[9:13 PM]  * Nightwatch    at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(MethodInfo mi, Object[] Parameters)
[9:13 PM]  * Nightwatch    at XmlRpcProxy6eba3ade-34fc-4ae3-8f00-0626dd4e9218.Search(SearchParams data)
[9:13 PM]  * Nightwatch    at ZeroKWeb.ResourceLinkProvider.GetJobjolMirrorLinks(String fileName, String springName)

[9:20 PM]  * Nightwatch 14.5.2015 21:21:05 Warning Error getting mirros from springfiles: System.Net.WebException: The request was aborted: The operation has timed out.
[9:20 PM]  * Nightwatch    at System.Net.HttpWebRequest.GetResponse()
[9:20 PM]  * Nightwatch    at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse(WebRequest request)
[9:20 PM]  * Nightwatch    at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
[9:20 PM]  * Nightwatch    at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(MethodInfo mi, Object[] Parameters)
[9:20 PM]  * Nightwatch    at XmlRpcProxy6eba3ade-34fc-4ae3-8f00-0626dd4e9218.Search(SearchParams data)
[9:20 PM]  * Nightwatch    at ZeroKWeb.ResourceLinkProvider.GetJobjolMirrorLinks(String fileName, String springName)

**Comment by lhog** [comment]
@sprunk, not totally sure how (and why) local Windows singularities related to the fact that http://zero-k.info/Maps/ doesn't see maps, uploaded to springfiles.

**Comment by sprunk** [comment]
AFAIK it doesn't actually check springfiles, only users' maps folder.

**Comment by lhog** [comment]
@sprunk , well I'm not sure. Here is ZKL log excerpt (from Linux though). It somehow hints something is missing server-side:

```
5/14/2015 11:18:01 PM: No server resource data for maps/apophis_v2_1.sd7, asking later
5/14/2015 11:18:02 PM: No server resource data for maps/tma-0_v1_1.sd7, asking later

**Comment by lhog** [comment]
I've traced the ZKL source code and found out that:

```
var mapCount = NativeMethods.GetMapCount(); (line 122 of UnitSync.cs)
```
returns 0 for two maps I have in the folder (one is universally known and one is new).

Is this expected?

P.S. Here is the unitsync.log from \engine\98.0.1-451-g0804ae1 folder:
```
Spring 98.0.1-451-g0804ae1 develop (Headless Unitsync)
Build Date & Time: Mar 22 2015 11:51:29
Build Environment: boost-105500, GNU libstdc++ version 20130531
Compiler Version:  gcc-4.8.1
Operating System:  Microsoft Windows
Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz; 16375MB RAM, 24565MB pagefile
Word Size:         32-bit (emulated)
Using configuration source: "e:\games\Spring_dev\engine\98.0.1-451-g0804ae1\springsettings.cfg"
[DataDirs] Portable Mode!
Using read-write data directory: e:\games\Spring_dev\engine\98.0.1-451-g0804ae1\
Using read-only data directory: C:\Users\AK\Documents\My Games\Spring\
Scanning: e:\games\Spring_dev\engine\98.0.1-451-g0804ae1\base
[unitsync] [UnitSync::Init] initialized 98.0.1-451-g0804ae1 develop (Headless Unitsync) (call 1) as client
[unitsync] deinitialized
```

**Comment by lhog** [comment]
Ok, I got it. The key issue is that unitsync (according to log) doesn't look into the proper directory. It looked into:

e:\games\Spring_dev\engine\98.0.1-451-g0804ae1\maps
C:\Users\AK\Documents\My Games\Spring\maps

but didn't look where it actually should look, i.e.:
e:\games\Spring_dev\maps

Once I have placed actual maps file into C:\Users\AK\Documents\My Games\Spring\maps the log said:
```
16.05.2015 19:21:36: New resource found: TMA-0 v1_1
16.05.2015 19:21:37: uploading TMA-0 v1_1 to server
16.05.2015 19:21:38: Map registered: TMA-0 v1_1
```

Can someone qualified fix it so that unitsync looks into the proper directory?  (Directory Zero-K.exe was lauched from)

**Comment by shaun0x00** [comment]
https://code.google.com/p/zero-k/source/detail?r=12394
Its not like this is new...

@Licho1 was clear:
"Please do not touch unitsync!! I told you it has zero effect on spring loading time of new map!
Only on the very first start of very new engine when you have tons and tons of maps."
"ZKL was made to avoid unitsync and massive time had been invested to achieve that.. for a reason, don't undo very reason of zkl existence!"

But this is not very clear. What does it mean, "ZKL was made to avoid unitsync"? Because it seems that ZKL relies on unitsync.

And anyway, why is this happening on client side, client which will then upload data to a database, without any kind of authentication? Is this all part of the grand scheme to avoid UnitSync?

I think we need a 5 lines summary explaining how it is supposed to work. If "ZKL was made to avoid unitsync", it is an important design goal that should be understood by contributors.

Same if it is a design goal to run UnitSync on clients, and trust everyone who is willing to spam database through soap services.

**Comment by Licho1** [comment]
ZKL is not meant to upload anything. Probably xponen uncomented some
ancient code. Autoregistrator on server is meant to do that.

2015-05-18 15:43 GMT+02:00 shaun <notifications@github.com>:

**Comment by lhog** [comment]
@Licho1 , but it does upload stuff! It's a second question why it does so, if other lobbies do it differently (and succesfully).
Is this what you call 'ancient code'?
```
var mapCount = NativeMethods.GetMapCount(); (line 122 of UnitSync.cs)
```

**Comment by Licho1** [comment]
this is definitely not meant to run, unitsync is meant to be default off and i insistent on it when talking with xponen. 
Xponen was meant to make it"optional on" but perhaps left it always on.

No client is meant to upload stuff by default.

**Comment by Anarchid** [comment]
If ZKL is not intended to process map data, then Autoregistrator is not functioning.

The incident with the asteroid map lasted what, a month?

**Comment by shaun0x00** [comment]
The side problem is that there is an unprotected service, ready to accept all kind of spam... whether @xponen enabled automatic upload to that service is irrelevant IMO. There would be no point in "enabling uploads" in the client if the server was not accepting it.

@Licho1, how do you intend to secure this service if you keep it open? Why is this even open?
Don't say "just look at the code", the answer to these questions can not be found in the code.

But the root problem seems to be that this database isn't updated properly by the "AutoRegistrator". People are confused on how the infrastructure is supposed to discover maps and try various workarounds, including ones that should not even exist.

So, can we get a high-level doc on:
- how maps are supposed to be discovered, downloaded by the server (from where?)
- how maps are supposed to be discovered, downloaded by the client (from where?)
- the autoregistrator and resource database

Just a 1-line, or few lines summary for each would be enough... then, we can know for sure how stuff is supposed to behave.

This discussion shows how confused is everyone:
- issue is initially closed because there is a way to upload stuff from a client (wtf?)... closed by someone who has access to the server, and thus, supposedly, a better understanding of the situation than others (my guess... seeing autoregistrator window should trigger a few questions)
- we waste time talking about client side stuff... a workaround...  while the problem is probably on the server (NW keeps spamming errors about maps... nobody is interested I guess...)

The code doesn't show what is supposed to happen.
So what is supposed to happen? What are the design goals?

Even the error logs are incomplete/confusing...
'14.05.2015 16:29:25: Unable to deserialize map AstroTurf v2_3 from the server: System.Net.WebException: The remote server returned an error: (404) Not Found.
sure... which remote server? which remote URL ?

Funny to see that "Unable to deserialize map" is actually a programmer joke... because, being unable to find the map metadata is enough to spill such an error... which is even more funny, because I think about all the error spam in #zkerror about not being able to extract the metadata... and how all this could be connected...

More fun #242 

Fun fun fun

**Comment by Orfelius** [comment]
Anarchid the asteroid incident lasted for 6 days or so.

**Comment by Licho1** [comment]
It's simple, its not meant to upload, server is not meant to listen.
Autoregistrator checks local folder for new files and indexes them using
it's own unitsync and pushes data to DB directly.

Maps folder of registrator runs wget from springfiles at regular intervals
to copy newest maps. This folder also serves as one of map/mod download
mirrors.

2015-05-18 19:03 GMT+02:00 Orfelius <notifications@github.com>:

**Comment by Anarchid** [comment]
The 404's would then suggest that the wget part is what's broken.

**Comment by shaun0x00** [comment]
My understanding: If the wget fails, no new file appear in the directory, so AutoRegistrator sees nothing, no new "map" row is added to database, and ZK infra knows nothing about it.

The 404 does not suggest that wget part is broken, because 404 is not generated by wget but by the client, when it tried to download the metadata...

Where is wget error log? Where is script? How often is it run? => this is for people who push map to springfiles and then enquire in #zkdev ... this way, they'll get a useful answer next time: They have to wait at least N minutes/hours before a problem can be suspected.

Then if it doesn't appear, someone need to check wget log... and if no problem can be found, then maybe understanding #242 would not be bad...

@Licho1, why do you say "This folder also serves as one of the map download mirrors"?
There is nothing in the code indicating that it is a mirror.
If I look at springfiles, zero-k.info isn't listed as a mirror for the few maps that I queried.
On zero-k.info/Maps details, I never see zero-k.info listed as a download mirror.
When I looked at the traffic generated by ZKL, I never saw maps being downloaded from zero-k.info.

**Comment by Licho1** [comment]
The script is on omega server in windows c:\projekty\update_maps.cmd
It's probably not auto scheduled for some reason, I run it manually once
now, someone should fix scheduler.

And yeah the mirror function appears to be broken as well...
stuff decays when I don't look I can only speak for how it originally was
and how its meant to work..

Another common issue is that AutoRegistrator can fail to start if DB was
modified. Reason for this is that AutoRegistrator is not auto deployed from
latest sources like other parts of infra. Dunno if its fixed already or not.


2015-05-18 23:49 GMT+02:00 shaun <notifications@github.com>:

**Comment by xponen** [comment]
@lhog  (Ivand) have debugged the issue and said it's because ZKL look at wrong folder.
```
It looked into:
e:\games\Spring_dev\engine\98.0.1-451-g0804ae1\maps
C:\Users\AK\Documents\My Games\Spring\maps

but didn't look where it actually should look, i.e.:
e:\games\Spring_dev\maps
```

Is probably easy typo somewhere.

**Comment by Anarchid** [comment]
> @lhog (Ivand) have debugged the issue and said it's because ZKL look at wrong folder.

The real oppression is that ZKL is not *supposed* to be responsible for maps.

**Comment by db81** [comment]
@lhog: The extra folders where unitsync (and spring) look for maps are given by the SpringData setting in springsettings.cfg

The SOAP services have been open for the entire world to exploit for as long as I can remember.

There's probably still a lot of ancient commented out code waiting to be uncommented by someone, perhaps a clean sweep to get rid of it could be useful.

**Comment by lhog** [comment]
@db81,
I (have) had "SpringData = E:\Games\Spring\" in springsettings.cfg, but it didn't make unitsync part of code look into that folder.

Anyway, it doesn't seem relevant, as that branch of code should never have been launched anyway.

**Comment by Anarchid** [comment]
The immediate problem seems to have been resolved; the problem with AutoRegistrator's wget component not autostarting is a separate issue.
