### ISSUE TITLE
Typing in Chat Crashes Lobby

### ISSUE THREAD

**Issue by Kshatriya77** [ZeroK-RTS/Zero-K-Infrastructure#744]
My lobby opens and appears normal until I type anything into the chatbar of any chatroom (battle, Zero-k, Clan chat). The lobby immediatly stops responding and has to be closed. I tried using the local data reset tool in the settings menu but that did not fix the problem. I am able to type into all other input boxes in the Zero-K lobby. Also, I can Paste text into chat rooms without it crashing. (Running Windows 7)

**Comment by Skasi** [comment]
More information on the crash:
http://zero-k.info/Forum/Thread/19775
http://zero-k.info/Forum/Thread/19820

Multiple users seem to be experiencing this issue.

**Comment by knorker** [comment]
another: http://zero-k.info/Forum/Thread/19942

**Comment by Anarchid** [comment]
Reportedly fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/58a1cc02882ed6ee1b3794f624b013933f543d5f

**Comment by Licho1** [comment]
@Anarchid  thats not the fix

**Comment by Licho1** [comment]
Basically, steamhandler can generate exception that cannot be recovered from, memory of the process is corrupted due to a bug in native lib.
Adding [HandleProcessCorruptedStateExceptions] to methods where such exceptions enter managed state can ensure they will be catched.

Also fixing/updating the actual native lib should be done too.

Ordinary exceptions in event handlers on "tasclient" class cannot bring ZKL down...

**Comment by Anarchid** [comment]
@Licho1 oops.

**Comment by KingRaptor** [comment]
What OS?
If Windows:
* What .NET version?
* What happens if you try the [.NET 4.0 version](http://zero-k.info/Wiki/Download)?

**Comment by knorker** [comment]
maybe fixed? http://zero-k.info/Forum/Thread/19942#143192

**Comment by Anarchid** [comment]
Closing until further incidents.
