### ISSUE TITLE
forbid resign vote for already resigned players

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#861]
Why is resigned player allowed to call resign vote... mostly it is abused by players who resign too early. It distracts players in the team which is already one less.

**Comment by Jamanno** [comment]
for example:
http://zero-k.info/Battles/Detail/381010

**Comment by Licho1** [comment]
You also need to know who resigned and send this to springie.

**Comment by ArchShaman** [comment]
How did I know sfire was somehow involved in this just by the title?

96 seconds is a little ridiculous though. But you can find one battle where sfire got the team to call for a resgn vote in 30 seconds.

**Comment by Jamanno** [comment]
in some games it distracts rest of team when every minute a resign vote appears mostly from resigned players...

**Comment by sprunk** [comment]
But this is the point of resign vote. For example when 9/10 people resigned, but last noob wants to fight to the last unit and will stall the game by another 20 minutes for everyone else.

**Comment by CrazyEddieTK** [comment]
Disagree.

Once you resign you are no longer a teammate. You are a spectator, and should have no more voice over the course of the game than any other spectator.

Resign vote is for saying "I think we should resign, but if everyone else thinks we should keep playing then I'll keep playing too."

Individual resign is for saying "Screw this, I'm done. If you guys want to keep going then you can do it without me."

**Comment by sprunk** [comment]
It*should* be that way, but currently resign is not only about the current game though. Clusterfuck culture means there is only ever one room, so to get another game going the current one has to end. In this way voteresign helps recycle people into another game faster.

The superior but harder alternative is to break the 1 room culture.

**Comment by CrazyEddieTK** [comment]
"we need to keep voteresign" - Sure, but there's no reason to let non-players participate. If you resign without your team resigning, you give up any say as to how long the game should last. And even if a hundred people are spectating and waiting for the game to end so they can play another one, TOO BAD. The game can and should last as long as the people still playing wish to play.

**Comment by sprunk** [comment]
>even if a hundred people are spectating and waiting for the game to end so they can play another one, TOO BAD

That's not how you build a playerbase and promote games to happen. People start leaving if they are not getting into a match.

"But people also leave when trolling specs abuse voteresign" -> yes, though you can mute a troll but can't punish a porcer.
"But people can move to another room themselves" -> yes, and they should, but 10 years of experience shows they never actually do.
"But there's votemove" -> yes, but it's not actually used either and is a fairly crappy solution.
"But there will be a matchmaker soon to solve this problem" -> nope, not in this decade. It is the ideal solution otherwise, though.

Figure out an effective, cheap way to recycle people into another game. Then voteresign can be made to only obey players.

**Comment by CrazyEddieTK** [comment]
If there are players who want to keep playing, and people waiting for them to finish, I will **_always_** prioritize the desires of the active in-game players over people who are a) just sitting around watching and b) who could go and start their own game any time they wanted to if they're really in that much of a hurry.

To do otherwise would be like telling Spassky and Fischer to hurry up and get on with it because you want go out to lunch with them and you're getting hungry. The game isn't for the spectators, it's for the players.

> Figure out an effective, cheap way to recycle people into another game. Then voteresign can be made to only obey players.

We do indeed need a good way to manage players and games (cough matchmaking cough) but I see no good reason why restricting voteresign to active players needs to wait for that.

> you can mute a troll but can't punish a porcer

The porcer doesn't deserve to be punished. If that's the strategy they've chosen, then that's their right as a player to do so. And if they choose to stay in the game until they are defeated, that also is their right as a player (short of deliberate and clear-cut efforts to delay the end of a game while disengaging from play, i.e. burrowing). If you don't like it, then stay in the game and keep playing until you can convince a majority of your teammates to abandon their lost cause.

Spectators should have no say in the matter. Teammates that have dropped out count as spectators and should have no say. And opponents can have a say by destroying their enemy as rapidly as possible.

**Comment by Licho1** [comment]
already implemented afaik it only lets ingame to vote
