### ISSUE TITLE
* and = tags break math

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#883]
These are used for multiplication and equals in math. For example see http://test.zero-k.info/Forum/Thread/20560

It would be good if they could be somehow escaped to prevent parsing.

**Comment by Anarchid** [comment]
Markdown uses asterisks for emphasis, and ZKI uses markdown-and-stuff since some time.

However, ZKI's markdown support is _incomplete_:
- In actual markdown, if you surround an * or _ with spaces, it’ll be treated as a literal asterisk or underscore.
- In actual markdown, if you indent a line with four spaces or a single tab, it will be treated as a code block, and asterisks will be considered literal within the code block.

Without these options, there is absolutely no way to avoid conversion of asterisks into emphasis, and consequently, no way to input actual asterisks. This is also the case for underscores, another Markdown emphasis character.

**Comment by Anarchid** [comment]
Apparently, one can use `{{{` and `}}}` to denote code blocks, which will have proper asterisks and underscores.
