### ISSUE TITLE
(installer/lobby) Cloud not load texture frome file bitmaps/other/debris2.tga 

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#895]
Maybe file not did not get written / downloaded properly?

http://zero-k.info/Forum/Thread/20766

**Comment by db81** [comment]
No one else has ever reported this error, looks impossible to reproduce and the original reporter has left.

**Comment by knorker** [comment]
> looks impossible to reproduce

Did someone try? see my post in thread

**Comment by db81** [comment]
If you delete a random file from Spring/pool/ and ZKL doesn't notice it after a restart you still haven't reproduced anything. In that case ZKL is right to assume files don't just randomly disappear from pool.

The error seems to have had self-corrected (and it can't be a write protection thing because that wouldn't cause a *single* missing file), which leads me to believe ZKL did notice it eventually and redownloaded.

**Comment by knorker** [comment]
What does  "delete a random file" have to do with this? I see nothing that makes me believe anything like that was done...

> The error seems to have had self-corrected 

Brackman wrote: fixed by "probably by copying Zero-K.exe to another folder."
(whatever that means. just the exe? meaning the installer?)
If the lobby does not work from previous location, that seems like error, and like something that can be tested.
(install lobby on clean system/clean VM)

> because that wouldn't cause a single missing file

iirc spring.exe just throws error at the first missing file and then quits
