### ISSUE TITLE
autohost settings produce unattractive matches

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#921]
This is about the official, public autohosts.

1) map selection
There exists system of "featured" maps and definitions if a map is suitable for 1v1, teams or FFA. Why is it not used? 
-Tiny maps should not be used in large-teams room because result is choatic Commander-deathmatch. 
-Joke-maps like: Trololo, Duke-Nukem or maps that by usual criteria would never get the "featured" (or even "supported") tag like superlong variants of IcyRun. Those should not be in any room.

2) Team sizes are too large.

3) "Funny" settings.
For example superhigh income-multiplicator so that within few seconds the income is +50metal.
It breaks every aspect of balance. This has no place in official room.

4) Broken maps or 'testing' maps.
Official rooms are a bad place to test maps.

**Comment by Skasi** [comment]
I think what you really want is matchmaking.

**Comment by knorker** [comment]
No.
This is about how autohosts should be configured, so players can meet there to play the game in a normal way. (If you want to discuss what "normal" means, then there are already plenty of threads on the forum to do excactly that.)

**Comment by Skasi** [comment]
Forum posts and polls have shown that players do not like player-limits. They also prefer playing a 10v10 on icy run over a 20x20 map that reduces FPS to a single digit.

Joke maps can **definitely** be supported. They often don't break any game mechanics, don't crash the game and don't cause any other technical problems. There's a specific "Silly" tag for joke maps, so neither "featured" nor "supported" need to be reserved for non-joke maps only.

>  It breaks every aspect of balance. This has no place in official room.

 &
> This is about how autohosts should be configured, so players can meet there to play the game in a normal way.

I don't think this is how rooms titled "All welcome!" are supposed to work. I am pretty sure I understand what you want: You want some sort of "competitive"/"serious" room, but just because a room has a star showing it's "official", doesn't mean it's supposed to be either of those. Official means "this room is not hosted by a private individual, it is public, vote-based and fully subject to moderation (ie. CoC applies)".

While there could indeed be a room titled "Competitive (team) games" or similar I think going straight towards matchmaking would remove issues like !vote spam, spec cheating and similar that all come with the current room-system and would affect competitive/serious rooms more negatively than others.

**Comment by knorker** [comment]
I do not think that this is very "competetive" or "serious" or "hardcore" or whatever it gets called sometimes.
It is simply the normal way. 
metalmulti=1.0 is default, so that is normal.
metalmuli=10 is not default, it alters the game, it is special.
If any rooms should be given special titles it is the un-normal ones, where the map is a singing face or where game is otherwise altered.

To me not wanting to play on a singing face, without bots & without stupid eco settings does not make a game "competetive" or "serious." (That would be ladder or tourney games)
But if there really is such low standards on gameplay, then name it "serious" or whatever.

>  going straight towards matchmaking
This change to autohosts is a realistic bugreport/request, but matchmaking is pipedream of of deus-ex-machina solution.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/989 https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/988

**Comment by Licho1** [comment]
We could simply tag all existing maps as allowed and remove those that arent, and review future maps..

**Comment by knorker** [comment]
FFA on small TEAMS host:
http://zero-k.info/Battles/Detail/417735

shitmap on small teams: (is this supposed to be "serious" or not?)
http://zero-k.info/Battles/Detail/417614

**Comment by Licho1** [comment]
MM fixes it

**Comment by knorker** [comment]
> MM fixes it

und dann:

![the big lobster pot](https://cloud.githubusercontent.com/assets/3044855/19161155/ef07bb46-8bf2-11e6-9231-b1bb22ba27bf.jpg)

**Comment by Licho1** [comment]
Well there are no autohsots now so you cannot really complain , there is nothing we can do about people hosting games they like the way they like.

**Comment by knorker** [comment]
You can do something about it: Offer a sensible infrastructure.
With good maplist, sensible teamsize, no shitty modoptions (all common sense) the game would attract and keep different kind of players. 

At the moment not really a choice for most players: either play a shitmatch or do not play at all.

**Comment by Licho1** [comment]
What do you mean, all maps are offered and non speed metalic are featured by default.
Modoptions are available simply all.. It's up to players..

**Comment by knorker** [comment]
Reality is that too many shit maps/options/crowded maps get played. Theory does not matter. 

> It's up to players..

Game gets the players it deserves.

**Comment by sprunk** [comment]
The only solution to shitmaps is to ban shitmaps. I think that would be the ideal solution but it would mean 90% of the playerbase leaves (because they love shitmaps: see how much they play them). Perhaps instead of permanently leaving, they go and host ZK on main Spring server but they will still play mostly shitmaps there. If almost everybody leaves then game won't attract anyone at all.

Personally I think the 90% is just stockholm syndrome and people would play (and like) proper games if they had no other choice. But the only way to check that would be to implement the clusterfuck ban which is a huge risk the other devs won't take.

Do you have a less risky way to force people to stop playing clusterfuck other than banning it?
Do you have a way to convince the other devs that speedmetal is unsustainable and the risk needs to be taken?

**Comment by knorker** [comment]
> Do you have a way to convince the other devs that speedmetal is unsustainable and the risk needs to be taken?

No. They have to come to realize it themself what kind of game and playerbase they want.
So far my facit is that they are shitty devs.

**Comment by Licho1** [comment]
Also just look at the drama caused by MM and removal of ranking for cluster games.
You are basically saying all those people screaming on forum are wrong and you should be even harsher at social engineering.

**Comment by knorker** [comment]
> just look at the drama caused by MM

like server and playerbase split?

> should be even harsher at social engineering.

social engineering was never nessecary because players _wanted_ non-shitty matches.
now game is dead. which is sad but always a chance to rebuild from anew. either for shitmatches or for nonshit.

**Comment by KingRaptor** [comment]
Using actual statistics instead of a snapshot from a <5 hour period with n=10:

42133 player minutes spent in no-bots games lasting at least 5 minutes in past 14 days
of which:
- 2612 p-minutes on maps tagged special
- 36807 p-minutes on non-special featured maps
    - of which 21025 p-minutes spent in games with less than 10 players
- 23023 p-minutes in games with less than 10 players in general

I am not convinced that 6.20% of total player minutes being spent on special maps constitutes some kind of silly map dystopia.

**Comment by knorker** [comment]
It is meaningless to compare playerminutes like that: It does not reflect what players encounter in lobby.

IcyRun is a normal map. But 8v8 IcyRun is still a silly shitgame. 
Per playerminutes it would counts towards the good games.

Whether the one lobsterPotRoom-shitmap-room contains 4 or 6 players or 12 players massively changes the playerminutes. But is that relevant for anyone? I think more relevant is that during that time no other matches were played.

The time-to-wait-until-game strongly depends on one factor:
The number of open rooms. When there is only one room it does not matter if it is hosting 2v2, 5v5 or 12v12. The recorded playerminutes differ but one has to wait the same amount of time until that match is finished. 
There are almost never two active rooms at once. MM did not change this.

In zeroK the teamsizes never depends on mapchoice or what teamsize players prefer.
Instead simply all online non-afk players are in one room. When small-teams matches get played it is simply because there was not enough players online for bigger teams. (Otherwise there would have been smallTeam and bigTeam room active in parallel, never happens)


> 42133 player minutes spent in no-bots games lasting at least 5 minutes in past 14 days

3009 playerminutes per day. Do you realize how little that actually is?
Get handful of friends or LAN party and they play for an hour and easily double that.
Or random series of 1v1 matches of BA: http://replays.springrts.com/player/85386/ on 2016-03-09
Two players on a saturday played a series of 1v1 matches that is like 1/3 of zK playerminutes.
The playerbase has shrunk so small, playerminutes have long become meaningless.

**Comment by KingRaptor** [comment]
> It is meaningless to compare playerminutes like that: It does not reflect what players encounter in lobby.

I consider it 10^3 times more meaningful than your anecdatum of a screenshot.

>IcyRun is a normal map. But 8v8 IcyRun is still a silly shitgame. 
Per playerminutes it would counts towards the good games.

I point you to the part where 5v5 or smaller games are still 57% of featured map playerminutes (and a higher match count than that, since they have fewer players to count). 

Now, sure, Icy Run 5v5 isn't a lot better than 8v8. On the other hand, you haven't shown any evidence that Icy Runs of any size are a significant contributor to the playerminutes at all. (On last run: Icy Run v2 games of any size made up 652 playerminutes out of 42954 total)


In any case, here are freshly fetched stats for raw battle minutes (not multiplied by player count):

- 6643 total
- 396 special maps
- 5909 featured maps
    - 4831 <= 10 players
- 5272 <= 10 players

Assuming only one game is visible at a time, that means SpeedMetal, Trololo et al. are what's for dinner 6.0% of the time. "Serious" non-clusterfuck games are up for 12.2 times as long as silly maps.

If we exclude games with <= 4 players (aiming to filter out those private games between groups of friends):

- 3035 total
- 221 special maps
- 2570 featured maps
    - 1492 <= 10 players
- 1664 <= 10 players

Silly maps are 7.28% of total battle time, serious non-clusterfuck games have 6.75 times the battle time.

>The playerbase has shrunk so small
playerminutes have long become meaningless.

This statement is missing at least one item in the logic chain (and more to the point, an explanation of how it disproves the disproof of a supposed preponderance of silly maps).

**Comment by knorker** [comment]
> On last run: Icy Run v2 games of any size made up 652 playerminutes out of 42954 total)

Do you not understand that "Icy Run" is just symbolic stand-in for _any_ normal map that gets played in overcrowded teamsizes? TitanDuel, FalsomDamCore, etc..


> >    The playerbase has shrunk so small playerminutes have long become meaningless.

>This statement is missing at least one item in the logic chain (and more to the point, an explanation of how it disproves the disproof of a supposed preponderance of silly maps).

The point is you can not use playerminutes as an arguement when the activity is too low to be measured that way. At some point it stops being meaningfull. A meaningful methode of measurement would be number of parallel active rooms.

"Silly maps" are only one subcategory of shitgames.
Shitgames can be:
-shit map
-normal map with too many players
-shitty modoptions
-shitty trolling players
-...
There are days when over whole evening imo no single match meets the criteria of a decent game.
Even a ration of 50% to me this is a preponderance of shitgames.

     

> Assuming only one game is visible at a time

This assumption is correct, and the problem.

**Comment by sprunk** [comment]
> There are almost never two active rooms at once. MM did not change this.

By "active" do you mean open or just existing (where game might be already started)?

MM only creates a room when a game is ready and kicks everyone out after game is over. So there's never an visible MM room on the list but there is always the MM queue which you can join and works the same as a "room" except it guarantees non-shitty settings (always a non-shitty, mapfeatured map with low playercount and no shitty modoptions).

Do you think the guarantee of non-shitty settings that MM gives is not enough to rally existing non-shitty players?

**Comment by knorker** [comment]
> By "active" do you mean open or just existing (where game might be already started)?

Resulting matches getting played. As listed in player profiles and replays list.
I only tried this MM for an hour, during which it got no games, so to be honest no idea how it really works.

> Do you think the guarantee of non-shitty settings that MM gives is not enough to rally existing non-shitty players?

There was also the "guarantees"  of a "serious room" and "small teams room" etc all which disappointed.
So I think: no.

**Comment by db81** [comment]
Why are you arguing with knorke...

**Comment by knorker** [comment]
because he plays even less than me and maybe has nothing better to do while idling in empty lobby

**Comment by Skasi** [comment]
> because he plays even less than me

knorke confirmed smurfing ZK. knorke confirmed ZK's biggest fanboi.

**Comment by knorker** [comment]
> Do you think the guarantee of non-shitty settings that MM gives is not enough to rally existing non-shitty players?

Oh, also unsuitable maps for MM:
http://zero-k.info/Battles/Detail/432576

And why? Because some mapfeaturer featured the map without having played a single match on it.
http://zero-k.info/Maps/Detail/53270#163875
There is no gurantee.
