### ISSUE TITLE
mission statistics & replays

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#928]
The mission "Tutorial - Running Start" has been played 26996 times
That would be ~20 plays per day...even with testruns and people playing it multiple times?
(and really, how often does a player re-play a tutorial?)

"Sandbox" has maybe more replay-value but ~30 daily plays is still huge. 
zero-K population count does not reflect those numbers.

It would be interessting to have numbers on:
-how many unique players have played a mission.
-how many players have completed a mission.
Some high-score lists exist, so maybe that is tracked already.

On http://zero-k.info/Battles one can set filter to show mission-replays but it only returns some strange collection of 1v1 on minichess map.
Being able to see newbs play SP could be insightful.

**Comment by Anarchid** [comment]
Singleplayer is generally larger than multiplayer for all games. 0ad has the ratio about 100x last time i checked (thousands of games played daily, at most 10 of them online).

There are also more *games* played online in skirmish mode, but this doesn't account for missions themselves.

Iirc multiplayer still generates more player minutes though because of massive player counts in the clusterfuck room.

I think missions should work offline to an extent, but an opt-in (or opt-out) upload of replays for analytics could be interesting.

**Comment by Licho1** [comment]
Now provided by GA, tweak as needed. And yes it is that much.
